const DB='slyhigh-vfx-data',VER='0.1.0',TYPES=['CLEANUP','SCREEN','GREENSCREEN','SET_EXTENSION','CG_OBJECT','CG_CHARACTER','DIGITAL_DOUBLE','ENVIRONMENT','VEHICLE','BEAUTY','MATTE_PAINTING','SIMULATION','OTHER'];
let db,state={schema:'slyhigh.vfxdata',schema_version:VER,operator:'',projects:[],activeProjectId:null,activeShotId:null,view:'shoot'};
const $=id=>document.getElementById(id), uid=()=>crypto.randomUUID?crypto.randomUUID():'id-'+Date.now()+Math.random(), now=()=>new Date().toISOString(), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function code(s){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,'_').replace(/^_|_$/g,'').slice(0,40)}
function openDB(){return new Promise((res,rej)=>{let r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{let d=r.result;if(!d.objectStoreNames.contains('kv'))d.createObjectStore('kv');if(!d.objectStoreNames.contains('media'))d.createObjectStore('media',{keyPath:'id'})};r.onsuccess=()=>{db=r.result;res()};r.onerror=()=>rej(r.error)})}
function store(n,m='readonly'){return db.transaction(n,m).objectStore(n)}
function get(n,k){return new Promise((res,rej)=>{let r=store(n).get(k);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function put(n,v,k){return new Promise((res,rej)=>{let r=k===undefined?store(n,'readwrite').put(v):store(n,'readwrite').put(v,k);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function save(){await put('kv',state,'state')} async function load(){let s=await get('kv','state');if(s)state=s}
function p(){return state.projects.find(x=>x.id===state.activeProjectId)}
function shots(pr=p()){return pr?pr.days.flatMap(d=>d.scenes.flatMap(s=>s.setups.flatMap(u=>u.shots.map(h=>({...h,_d:d,_s:s,_u:u}))))):[]}
function shot(){return shots().find(x=>x.id===state.activeShotId)}
function raw(){let pr=p();if(!pr)return null;for(let d of pr.days)for(let s of d.scenes)for(let u of s.setups){let h=u.shots.find(x=>x.id===state.activeShotId);if(h)return h}}
function cam(id){let x=p()?.cameras.find(y=>y.id===id);return x?x.code+' · '+[x.make,x.model].filter(Boolean).join(' '):'—'} function lens(id){let x=p()?.lenses.find(y=>y.id===id);return x?x.code+' · '+[x.make,x.model].filter(Boolean).join(' '):'—'}
function payload(){return {schema:'slyhigh.vfxdata',schema_version:VER,exported_at:now(),operator:state.operator,project:JSON.parse(JSON.stringify(p()))}}
function dl(name,b){let a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportJSON(){dl(p().code+'_VFX_DATA.json',new Blob([JSON.stringify(payload(),null,2)],{type:'application/json'}))}
function q(v){return '"'+String(v??'').replace(/"/g,'""')+'"'} function exportCSV(){let a=[['day','date','scene','setup','shot','take','types','camera','lens','focal_mm','focus_m','aperture','ei','wb','shutter','fps','measurements','references','plates','notes','shutter_mode','shutter_fraction_denominator','shutter_seconds']];for(let d of p().days)for(let s of d.scenes)for(let u of s.setups)for(let h of u.shots){let c=h.camera||{};a.push([d.code,d.date,s.code,u.code,h.code,h.take,(h.types||[]).join('|'),cam(c.cameraId),lens(c.lensId),c.focal,c.focus,c.aperture,c.ei,c.wb,c.shutter,c.fps,h.measurements.length,h.media.length,h.plates.length,h.notes.length,c.shutterMode||'angle',c.shutterFraction,shutterSeconds(c)])}dl(p().code+'_SHOTS.csv',new Blob([a.map(r=>r.map(q).join(',')).join('\n')],{type:'text/csv'}))}

// UI 0.2; the original IndexedDB name, stores, UUIDs and schema remain unchanged.
const BUILD='0.2.1', icons={shoot:'<path d="M4 6h16v14H4zM4 10h16M8 3v4M16 3v4"/>',library:'<rect x="4" y="5" width="16" height="15" rx="2"/><path d="M8 5V3m8 2V3M4 10h16m-8 0v10"/>',tools:'<path d="M14 5a5 5 0 0 0-6 6L3 16l5 5 5-5a5 5 0 0 0 6-6l-4 4-5-5z"/>',export:'<path d="M12 3v12m-4-4 4 4 4-4M4 15v6h16v-6"/>',camera:'<path d="M3 7h5l2-3h4l2 3h5v13H3z"/><circle cx="12" cy="13" r="4"/>'};
let route={page:'projects'},navStack=[],objectURLs=[],captureContext=null,pendingCapture=null,editingLib=null,customField=null,toastTimer,saveError=false;
const icon=k=>'<svg viewBox="0 0 24 24" aria-hidden="true">'+icons[k]+'</svg>', pretty=s=>String(s||'').replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase()), opt=(v,l,selected)=>'<option value="'+esc(v)+'" '+(String(v)===String(selected)?'selected':'')+'>'+esc(l??v)+'</option>';
function field(id,label,value='',type='text',extra=''){return '<div class="field"><label for="'+id+'">'+label+'</label><input id="'+id+'" type="'+type+'" value="'+esc(value??'')+'" '+extra+'></div>'}
function selectField(id,label,values,value='',extra=''){return '<div class="field"><label for="'+id+'">'+label+'</label><select id="'+id+'" '+extra+'>'+values.map(v=>Array.isArray(v)?opt(v[0],v[1],value):opt(v,pretty(v),value)).join('')+'</select></div>'}
function section(title,count=''){return '<div class="section"><h2>'+title+'</h2><span>'+count+'</span></div>'}
function row(title,sub,action,count='',prefix=''){return '<button class="list-row" onclick="'+action+'">'+prefix+'<span class="grow"><b>'+esc(title)+'</b><small>'+esc(sub)+'</small></span>'+(count!==''?'<span class="count">'+esc(count)+'</span>':'')+'<span class="chevron">›</span></button>'}
function pageTop(title,backLabel='Back'){return '<div class="backbar"><button class="back" onclick="back()"><span>‹</span>'+esc(backLabel)+'</button></div><h1 class="page-title">'+esc(title)+'</h1>'}
function toast(s){clearTimeout(toastTimer);$('toast').textContent=s;$('toast').classList.add('show');toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2400)}
function setSaveStatus(text,failed=false){$('saveStatus').innerHTML=(failed?'':'<i></i>')+esc(text);$('saveStatus').classList.toggle('danger',failed)}
function put(n,v,k){return new Promise((resolve,reject)=>{const tx=db.transaction(n,'readwrite');const os=tx.objectStore(n);k===undefined?os.put(v):os.put(v,k);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('Storage transaction aborted'))})}
async function save(){setSaveStatus('SAVING');try{await put('kv',state,'state');saveError=false;setSaveStatus('SAVED ON DEVICE')}catch(e){saveError=true;setSaveStatus('NOT SAVED · RETRY',true);toast('Could not save. Free device storage, then tap Retry.');throw e}}
$('saveStatus').addEventListener('click',()=>{if(saveError)save().catch(()=>{})});
function go(page,extra={},replace=false){if(!replace){navStack.push({...route,scroll:scrollY});history.pushState({sly:true},'')}route={page,projectId:state.activeProjectId,shotId:state.activeShotId,...extra};render();window.scrollTo(0,0)}
function back(){if(navStack.length){history.back()}else go(p()?'shoot':'projects',{},true)}
window.addEventListener('popstate',()=>{route=navStack.pop()||{page:p()?'shoot':'projects'};if('projectId'in route){state.activeProjectId=route.projectId;state.activeShotId=route.shotId;save().catch(()=>{})}render();scrollTo(0,route.scroll||0)});
function view(page){state.view=page;save().catch(()=>{});go(page)}
function closeDlg(){$('dlg').close()}
function render(){if(!('projectId'in route)){route.projectId=state.activeProjectId;route.shotId=state.activeShotId}objectURLs.forEach(URL.revokeObjectURL);objectURLs=[];const page=route.page;document.body.dataset.page=page;renderCaptureDock();const parent=['shot','newShot','measure','references','measurements','catalog','legacy'].includes(page)?'shoot':['camera','lens'].includes(page)?'library':['screen','markers','distortion','scale'].includes(page)?'tools':page;$('nav').hidden=!p()||['newProject','newShot','camera','lens','measure','catalog','captureError','custom','shotTypes','projectSettings'].includes(page);$('nav').innerHTML=['shoot','library','tools','export'].map(k=>'<button class="'+(parent===k?'active':'')+'" onclick="view(\''+k+'\')">'+icon(k)+'<span>'+k.toUpperCase()+'</span></button>').join('');const pages={projects:projectsScreen,newProject:newProjectScreen,shoot:shootScreen,shot:shotScreen,newShot:newShotScreen,library:libraryScreen,camera:libraryEditor,lens:libraryEditor,measure:measurementScreen,references:referencesScreen,measurements:measurementsScreen,catalog:catalogScreen,captureError:captureErrorScreen,custom:customScreen,shotTypes:shotTypesScreen,projectSettings:projectSettingsScreen,tools:toolsScreen,screen:screenAssetScreen,markers:markerScreen,distortion:distortionScreen,scale:scaleScreen,export:exportScreen,legacy:legacyScreen};if(!p()&&!['projects','newProject'].includes(page)){route={page:'projects'};return render()}(pages[route.page]||projectsScreen)()}
function projectsScreen(){$('main').innerHTML='<section class="hero"><div class="eyebrow accent">ON-SET ACQUISITION / '+BUILD+'</div><h1>The set.<br>Every detail.</h1><p class="lead">Offline VFX acquisition tool.<br>Capture now. Keep the context.</p></section>'+section('Projects',String(state.projects.length).padStart(2,'0'))+'<div class="list">'+(state.projects.length?state.projects.map(pr=>row(pr.name,pr.code,"switchProject('"+pr.id+"')",shots(pr).length+' shots')).join(''):'<div class="empty"><b>Your next production starts here.</b>Projects and captures stay on this device.</div>')+'</div><button class="primary action" onclick="go(\'newProject\')">+ New project</button><p class="footer-note">REAL WORLD → STRUCTURED VFX DATA<br>READY FOR WHAT COMES NEXT.</p>'}
function newProjectScreen(){$('main').innerHTML=pageTop('New project','Projects')+'<form onsubmit="createProject(event)">'+field('pn','Display name','','text','required oninput="if(!pc.dataset.edited)pc.value=code(this.value)"')+field('pc','Project code','','text','required oninput="this.dataset.edited=\'true\'" onblur="this.value=code(this.value)"')+'<p class="helper" style="margin-top:-14px;margin-bottom:24px">Generated from the name. You can change it before creating.</p>'+field('op','Operator',state.operator)+'<button class="primary action">Create project</button></form>'}
async function createProject(e){e.preventDefault();const name=$('pn').value.trim(),pc=code($('pc').value);if(!name||!pc)return toast('Enter a name and a valid project code.');if(state.projects.some(x=>x.code===pc))return toast('That project code already exists.');const pr={id:uid(),name,code:pc,created:now(),cameras:[],lenses:[],days:[]};state.projects.push(pr);state.activeProjectId=pr.id;state.activeShotId=null;state.operator=$('op').value.trim();await save();go('shoot',{},true);toast('Project created')}
async function switchProject(id){state.activeProjectId=id;state.activeShotId=shots().find(x=>x.id===state.activeShotId)?.id||shots().at(-1)?.id||null;await save();go('shoot')}
function shootScreen(){const pr=p(),all=shots();$('main').innerHTML='<div class="backbar"><button class="back" onclick="go(\'projects\')"><span>‹</span>Projects</button><button class="text-button" onclick="go(\'projectSettings\')">Project settings</button></div><section class="hero" style="padding-top:20px"><div class="eyebrow accent">'+esc(pr.code)+'</div><h1>'+esc(pr.name)+'</h1><p class="lead">'+all.length+' shots · '+pr.days.length+' shoot days</p></section><button class="primary" onclick="go(\'newShot\')">+ New shot</button>'+section('Shot log',all.length?all.length+' TOTAL':'')+(all.length?pr.days.slice().reverse().map(d=>'<div class="section"><h2>'+esc(d.code)+'</h2><span>'+esc(d.date)+'</span></div><div class="list">'+all.filter(x=>x._d.id===d.id).map(h=>row(h.code,'SC '+h._s.code+' · SETUP '+h._u.code,"selectShot('"+h.id+"')",'TAKE '+String(h.take||1).padStart(2,'0'))).join('')+'</div>').join(''):'<div class="empty"><b>Ready when you are.</b>Create a shot. Camera settings carry forward, so you only change what changed.</div>')}
async function selectShot(id){state.activeShotId=id;await save();go('shot')}
function newShotScreen(){
 const prev=shot()||shots().at(-1);route.inheritId=prev?.id;route.newTypes||=[];
 $('main').innerHTML=pageTop('New shot',p().name)+'<form class="shot-form" onsubmit="createShot(event)"><div class="slate slate-form"><div class="slate-production"><span class="eyebrow">PRODUCTION</span><b>'+esc(p().name)+'</b></div><div class="slate-inputs">'+field('sh','Shot','','text','required autocapitalize="characters"')+field('sc','Scene',prev?._s.code||'','text','required')+field('su','Setup',prev?._u.code||'','text','required')+'</div></div><div id="shotTypes">'+shotTypeFields(route.newTypes)+'</div>'+(prev?'<label class="switch"><input id="inherit" type="checkbox" checked><span>INHERIT PREVIOUS SHOT SETTINGS<small>From '+esc(prev.code)+' · camera state only</small></span></label>':'<p class="helper">Your first shot starts with an empty camera state.</p>')+'<details class="date-detail"><summary>Shoot date <span id="dateSummary">'+localDate()+'</span><small>From this device · change if needed</small></summary>'+field('sd','Shoot date',localDate(),'date','required onchange="document.getElementById(\'dateSummary\').textContent=this.value"')+'</details><button class="primary action">Create shot</button></form>';
}
async function createShot(e){
 e.preventDefault();const pr=p(),date=$('sd').value,scene=$('sc').value.trim(),setup=$('su').value.trim().toUpperCase(),sh=$('sh').value.trim().toUpperCase();
 if(!scene||!setup||!sh)return toast('Scene, setup and shot are required.');if(shots().some(h=>h.code===sh))return toast('This shot code already exists.');
 const u=ensureSetup(pr,date,scene,setup),prev=$('inherit')?.checked?shots().find(h=>h.id===route.inheritId):null,camera=prev?structuredClone(prev.camera||{}):{cameraId:null,lensId:null};
 const h={id:uid(),code:sh,types:[...(route.newTypes||[])],take:1,camera,measurements:[],media:[],plates:[],notes:[],voice:[],created:now()};
 if(prev){h.inherited_from=prev.id;h.cameraProvenance=Object.fromEntries(Object.entries(camera).filter(([k,v])=>v!==null&&v!==''&&k!=='updated').map(([k])=>[k,'INHERITED']))}
 u.shots.push(h);state.activeShotId=h.id;await save();go('shot',{},true);
}
function provenance(h,k){const v=h.camera?.[k];return v===null||v===undefined||v===''?'EMPTY':h.cameraProvenance?.[k]||'USER ENTERED'}
function cameraRow(key,label,unit='',options=null,numeric=true){const h=raw(),c=h.camera||{},v=c[key]??'',tag=provenance(h,key),id='cs_'+key;let control;if(options){const known=options.map(x=>Array.isArray(x)?String(x[0]):String(x));let opts=[['',''],...options];if(v!==''&&!known.includes(String(v)))opts.push([v,String(v)]);control='<select id="'+id+'" onchange="chooseCameraValue(\''+key+'\',this.value,'+numeric+')">'+opts.map(x=>Array.isArray(x)?opt(x[0],x[1],v):opt(x,x,v)).join('')+(key.endsWith('Id')?'':opt('__custom','Custom / Other',v))+'</select>'}else control='<input id="'+id+'" aria-label="'+label+'" type="'+(numeric?'number':'text')+'" '+(numeric?'step="any" inputmode="decimal" min="0"':'')+' value="'+esc(v)+'" oninput="updateCamera(\''+key+'\',this.value,'+numeric+')">';return '<div class="setting"><label for="'+id+'">'+label+'<small id="prov_'+key+'">'+tag+'</small></label>'+control+(unit?'<span class="unit">'+unit+'</span>':'')+'</div>'}
function shotScreen(){
 const h=shot(),r=raw();if(!h){route={page:'shoot'};return render()}
 const active=(r.notes||[]).filter(n=>n.take===r.take).at(-1);
 const cameraHTML=cameraRow('cameraId','Camera','',p().cameras.map(x=>[x.id,x.code+' · '+x.model]),false)+cameraRow('lensId','Lens','',p().lenses.map(x=>[x.id,x.code+' · '+x.model]),false)+cameraRow('focal','Focal','mm')+cameraRow('focus','Focus','m')+cameraRow('aperture','T / F stop')+cameraRow('ei','EI / ISO')+cameraRow('wb','White balance','K',['2800','3200','4300','5600','6500'])+cameraRow('fps','Frame rate','fps',FPS)+'<div id="shutterControl">'+shutterControls()+'</div>'+cameraRow('nd','ND','',['Clear','0.3','0.6','0.9','1.2','1.5','1.8','2.1'],false)+cameraRow('movement','Movement','',['TRIPOD','HANDHELD','DOLLY','CRANE','GIMBAL','DRONE','VEHICLE_RIG','MOTION_CONTROL'].map(x=>[x,pretty(x)]),false)+cameraRow('sensorMode','Sensor mode','',null,false)+cameraRow('color','Color / gamma','',GAMMAS[p().cameras.find(x=>x.id===r.camera.cameraId)?.make]||[...new Set(Object.values(GAMMAS).flat())],false);
 $('main').innerHTML='<div class="backbar"><button class="back" onclick="go(\'shoot\')"><span>‹</span>'+esc(p().name)+'</button><button class="text-button" onclick="go(\'newShot\')">+ New shot</button></div>'+slateHeader(h,r)+'<div class="shot-workspace"><section class="camera-column">'+section('Camera state',r.inherited_from?'INHERITED → EDITABLE':'AUTOSAVE')+'<div class="settings">'+cameraHTML+'</div></section><section class="shot-side">'+section('Shot type')+'<div id="shotTypes">'+shotTypeFields(r.types)+'</div>'+section('Capture')+'<div class="capture-actions"><button class="primary" onclick="capture()">'+icon('camera')+' Capture photo / video</button><button class="secondary" onclick="go(\'measure\')">+ Add measurement</button></div>'+section('Notes','TAKE '+String(r.take).padStart(2,'0'))+'<div class="field"><label for="shotNote">Note · autosaved</label><textarea id="shotNote" rows="4" oninput="updateNote(this.value)" data-id="'+esc(active?.id||'')+'">'+esc(active?.text||'')+'</textarea><p class="helper">Type or use keyboard dictation.</p></div>'+r.notes.filter(n=>n.id!==active?.id).slice().reverse().map(n=>'<div class="note-item"><span class="meta">TAKE '+String(n.take||1).padStart(2,'0')+'</span><p>'+esc(n.text)+'</p></div>').join('')+section('Shot records')+'<div class="list">'+row('References','Photos & videos',"go('references')",r.media.length)+row('Measurements','Values, method & confidence',"go('measurements')",r.measurements.length)+((r.plates?.length||r.voice?.length)?row('Previous captures','Plates & audio from earlier versions',"go('legacy')",(r.plates?.length||0)+(r.voice?.length||0)):'')+'</div><details class="date-detail"><summary>Shoot date <span>'+esc(h._d.date)+'</span><small>Change only when needed</small></summary>'+field('editShotDate','Shoot date',h._d.date,'date','required onchange="updateShotDate(this.value)"')+'</details></section></div>';
}
async function updateCamera(key,value,numeric){const h=raw();let v=value===''?null:numeric?Number(value):value;if(numeric&&v!==null&&(!Number.isFinite(v)||v<0))return;h.camera||={};h.camera[key]=v;h.camera.updated=now();h.cameraProvenance||={};h.cameraProvenance[key]=v===null?'EMPTY':'USER ENTERED';if(key==='cameraId'&&v){const equipment=p().cameras.find(x=>x.id===v);for(const k of ['fps','color'])if((h.camera[k]===null||h.camera[k]===undefined||h.camera[k]==='')&&equipment?.[k]){h.camera[k]=equipment[k];h.cameraProvenance[k]='PRESET';const control=$('cs_'+k);if(control){if(control.tagName==='SELECT'&&![...control.options].some(o=>o.value===String(equipment[k])))control.add(new Option(equipment[k],equipment[k]));control.value=String(equipment[k]);$('prov_'+k).textContent='PRESET'}}}if(key==='fps'||key==='cameraId'){syncShutter(h.camera);if($('shutterControl'))$('shutterControl').innerHTML=shutterControls()}const label=$('prov_'+key);if(label)label.textContent=h.cameraProvenance[key];await save()}
function chooseCameraValue(key,value,numeric){if(value==='__custom'){customField={key,numeric};go('custom')}else updateCamera(key,value,numeric)}
function customScreen(){const {key,numeric}=customField;$('main').innerHTML=pageTop('Custom '+pretty(key),'Shot')+'<form onsubmit="saveCustom(event)">'+field('customValue',pretty(key),raw().camera[key]??'',numeric?'number':'text',numeric?'step="any" min="0" required':'required')+'<button class="primary">Use value</button></form>'}
async function saveCustom(e){e.preventDefault();await updateCamera(customField.key,$('customValue').value,customField.numeric);back()}
async function updateNote(text){const h=raw(),el=$('shotNote');let n=h.notes.find(x=>x.id===el.dataset.id);if(!n){if(!text.trim())return;n={id:uid(),tag:'GENERAL',text:'',take:h.take,created:now()};h.notes.push(n);el.dataset.id=n.id}n.text=text;n.updated=now();await save()}
async function take(n){const h=raw();h.take=Math.max(1,(h.take||1)+n);render();$('takeNumber').classList.add('take-flash');navigator.vibrate?.(15);toast('TAKE '+String(h.take).padStart(2,'0'));await save()}
function shotTypesScreen(){$('main').innerHTML=pageTop('Shot type',raw().code)+'<div id="shotTypes">'+shotTypeFields(raw().types)+'</div><button class="primary action" onclick="back()">Done</button>'}
async function toggleType(t,b){const h=raw();h.types=h.types.includes(t)?h.types.filter(x=>x!==t):[...h.types,t];b.classList.toggle('on');b.setAttribute('aria-pressed',h.types.includes(t));await save()}
function libraryScreen(){
 $('main').innerHTML='<section class="hero"><div class="eyebrow accent">'+esc(p().code)+' / LIBRARY</div><h1>Your kit.<br>Always ready.</h1><p class="lead">Register once. Reuse on every shot.</p></section><div class="library-columns"><section>'+section('Cameras',p().cameras.length)+'<div class="list">'+p().cameras.map(x=>row(x.code,[x.make,x.model].filter(Boolean).join(' '),"editLibrary('camera','"+x.id+"')")).join('')+'</div><button class="secondary action" onclick="editLibrary(\'camera\')">+ Add camera</button></section><section>'+section('Lenses',p().lenses.length)+'<div class="list">'+p().lenses.map(x=>row(x.code,[x.make,x.model].filter(Boolean).join(' '),"editLibrary('lens','"+x.id+"')")).join('')+'</div><button class="secondary action" onclick="editLibrary(\'lens\')">+ Add lens</button></section></div>';
}
function editLibrary(kind,id){const list=kind==='camera'?p().cameras:p().lenses;editingLib={kind,id,draft:structuredClone(list.find(x=>x.id===id)||{}),provenance:{}};editingLib.provenance=structuredClone(editingLib.draft.provenance||{});go(kind)}
function presetOptions(list){return '<option value=""></option>'+[...new Set(list.map(x=>x.make))].map(make=>'<optgroup label="'+esc(make)+'">'+list.map((x,i)=>x.make===make?opt(i,x.model,''): '').join('')+'</optgroup>').join('')+'<option value="custom">Custom / Other</option>'}
function libraryEditor(){const ed=editingLib,isCam=ed.kind==='camera',d=ed.draft;let html=pageTop((ed.id?'Edit ':'Add ')+ed.kind,'Library')+'<form onsubmit="saveLibrary(event)">';if(!isCam)html+=selectField('libType','Lens type',['','PRIME','ZOOM','ANAMORPHIC','OTHER'],d.type||'','onchange="libEdit(\'type\',this.value)"');html+='<div class="field"><label for="libPreset">Select '+ed.kind+'</label><select id="libPreset" onchange="applyPreset(this.value)">'+presetOptions(isCam?CAMERAS:LENSES)+'</select><p class="helper">Preset values are starting points. Confirm the actual equipment on set.</p></div>';const fields=isCam?[['code','Camera ID'],['make','Manufacturer'],['model','Model'],['sensor','Sensor format'],['mount','Lens mount']]:[['code','Lens ID'],['make','Manufacturer'],['model','Model'],['range','Focal / range'],['mount','Mount']];html+=fields.map(([key,label])=>field('lib_'+key,label,d[key]||'','text',(key==='code'||key==='model'?'required ':'')+'oninput="libEdit(\''+key+'\',this.value)"')+'<p class="helper" id="libprov_'+key+'" style="margin-top:-18px;margin-bottom:23px">'+libProvenance(key)+'</p>').join('');if(isCam){const gamma=GAMMAS[d.make]||[...new Set(Object.values(GAMMAS).flat())];html+=selectField('libColor','Color / gamma',[['',''],...gamma.map(x=>[x,x]),...(d.color&&!gamma.includes(d.color)?[[d.color,d.color]]:[]),['custom','Custom / Other']],d.color||'','onchange="gammaChange(this.value)"')+'<div id="customGamma" '+(ed.customGamma?'':'hidden')+'>'+field('libColorCustom','Custom color / gamma',ed.customGamma?d.color:'','text','oninput="libEdit(\'color\',this.value)"')+'</div><p class="helper" id="libprov_color" style="margin-top:-14px">'+libProvenance('color')+'</p>'+selectField('libFps','Default FPS',[['',''],...FPS.map(x=>[x,x]),...(d.fps&&!FPS.includes(String(d.fps))?[[d.fps,d.fps]]:[]),['custom','Custom']],d.fps??'','onchange="libFpsChange(this.value)"')+'<div id="customFps" hidden>'+field('libFpsCustom','Custom FPS','','number','min="0.001" step="any" oninput="libEdit(\'fps\',this.value===\'\'?null:Number(this.value))"')+'</div>'}html+='<button class="primary action">Save '+ed.kind+'</button></form>'+(ed.id?'<button class="danger-button" onclick="confirmLibraryDelete()">Delete '+ed.kind+'</button>':'');$('main').innerHTML=html}
function libProvenance(key){let v=editingLib.draft[key];return !v&&v!==0?'EMPTY':editingLib.provenance[key]||'USER ENTERED'}
function libEdit(key,value){editingLib.draft[key]=value;editingLib.provenance[key]=value===''||value===null?'EMPTY':'USER ENTERED';const el=$('libprov_'+key);if(el)el.textContent=editingLib.provenance[key]}
function applyPreset(index){if(index==='')return;if(index==='custom'){toast('All fields are editable.');return}const preset=(editingLib.kind==='camera'?CAMERAS:LENSES)[Number(index)];if(!preset)return;Object.assign(editingLib.draft,preset);for(const [k,v] of Object.entries(preset))editingLib.provenance[k]=v?'PRESET':'EMPTY';editingLib.customGamma=false;libraryEditor();$('libPreset').value=index}
function gammaChange(v){if(v==='custom'){editingLib.customGamma=true;$('customGamma').hidden=false;$('libColorCustom').value=editingLib.draft.color||'';$('libColorCustom').focus()}else{editingLib.customGamma=false;$('customGamma').hidden=true;libEdit('color',v)}}
function libFpsChange(v){$('customFps').hidden=v!=='custom';if(v==='custom'){$('libFpsCustom').value=editingLib.draft.fps??'';$('libFpsCustom').focus()}else libEdit('fps',v===''?null:Number(v))}
async function saveLibrary(e){e.preventDefault();const ed=editingLib,d=ed.draft,list=ed.kind==='camera'?p().cameras:p().lenses;if(!d.code?.trim()||!d.model?.trim())return toast('An ID and model are required.');if(list.some(x=>x.id!==ed.id&&x.code===d.code.trim()))return toast('That equipment ID already exists.');if(d.fps!==undefined&&d.fps!==null&&(!Number.isFinite(d.fps)||d.fps<=0))return toast('FPS must be a positive number.');d.code=d.code.trim();d.id=ed.id||uid();d.provenance=ed.provenance;const at=list.findIndex(x=>x.id===d.id);if(at<0)list.push(d);else list[at]=d;await save();go('library',{},true);toast(pretty(ed.kind)+' saved')}
function confirmLibraryDelete(){const ed=editingLib,key=ed.kind==='camera'?'cameraId':'lensId',count=shots().filter(h=>h.camera?.[key]===ed.id).length;$('dlgBody').innerHTML='<h2>Delete '+esc(ed.draft.code)+'?</h2><p>'+esc(ed.draft.code)+' is used by '+count+' shots.</p><p class="helper">The equipment will be unassigned. Recorded camera-state values remain.</p><div class="row"><button onclick="closeDlg()">Cancel</button><button class="danger-fill" onclick="deleteLibrary()">Delete and unassign</button></div>';$('dlg').showModal()}
async function deleteLibrary(){const ed=editingLib,key=ed.kind==='camera'?'cameraId':'lensId';for(const d of p().days)for(const s of d.scenes)for(const u of s.setups)for(const h of u.shots)if(h.camera?.[key]===ed.id){h.camera[key]=null;if(h.cameraProvenance)h.cameraProvenance[key]='EMPTY'}const prop=ed.kind==='camera'?'cameras':'lenses';p()[prop]=p()[prop].filter(x=>x.id!==ed.id);await save();closeDlg();go('library',{},true);toast('Deleted and unassigned')}
function projectSettingsScreen(){$('main').innerHTML=pageTop('Project settings',p().name)+'<form onsubmit="saveProjectSettings(event)">'+field('projectName','Display name',p().name,'text','required')+'<p class="meta">PROJECT CODE · '+esc(p().code)+'</p><p class="helper">The project code stays stable when the display name changes.</p>'+field('projectOperator','Operator',state.operator)+'<button class="primary action">Save changes</button></form><button class="danger-button" onclick="confirmProjectDelete()">Delete project</button>'}
async function saveProjectSettings(e){e.preventDefault();if(!$('projectName').value.trim())return;p().name=$('projectName').value.trim();state.operator=$('projectOperator').value.trim();await save();back()}
function confirmProjectDelete(){$('dlgBody').innerHTML='<h2>Delete '+esc(p().name)+'?</h2><p>This removes this project and its captures from this device.</p>'+field('deleteCode','Type '+esc(p().code),'','text','autocomplete="off" oninput="deleteProjectBtn.disabled=this.value!==p().code"')+'<div class="row"><button onclick="closeDlg()">Cancel</button><button id="deleteProjectBtn" class="danger-fill" disabled onclick="deleteProject()">Delete project</button></div>';$('dlg').showModal()}
async function deleteProject(){if($('deleteCode').value!==p().code)return;const project=p(),mediaIds=new Set(shots().flatMap(h=>[...(h.media||[]),...(h.plates||[]),...(h.voice||[])].map(m=>m.mediaId)));const next=structuredClone(state);next.projects=next.projects.filter(x=>x.id!==project.id);next.activeProjectId=null;next.activeShotId=null;await new Promise((resolve,reject)=>{const tx=db.transaction(['kv','media'],'readwrite');tx.objectStore('kv').put(next,'state');const os=tx.objectStore('media');for(const id of mediaIds)if(id)os.delete(id);const req=os.openCursor();req.onsuccess=()=>{const cur=req.result;if(cur){if(cur.value.projectId===project.id)cur.delete();cur.continue()}};tx.oncomplete=resolve;tx.onerror=e=>reject(tx.error||e.target.error||new Error('Storage write failed'));tx.onabort=()=>reject(tx.error||new Error('Storage transaction aborted'))});state=next;closeDlg();navStack=[];go('projects',{},true);toast('Project deleted')}
function capture(){if(captureSaving)return toast('Saving capture…');const h=raw();captureContext={projectId:p().id,shotId:h.id,take:h.take,created:now()};$('captureInput').value='';$('captureInput').click()}
$('captureInput').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;pendingCapture={file:f,context:{...captureContext}};await persistCapture()});
let captureSaving=false;
function mediaBlob(entry){return entry.blob instanceof Blob?entry.blob:new Blob([entry.bytes],{type:entry.type||'application/octet-stream'})}
function commitCapture(record){return new Promise((resolve,reject)=>{const tx=db.transaction(['media','kv'],'readwrite');tx.objectStore('media').put(record);tx.objectStore('kv').put(state,'state');tx.oncomplete=resolve;tx.onerror=e=>reject(tx.error||e.target.error||new Error('Storage write failed'));tx.onabort=()=>reject(tx.error||new Error('Storage transaction aborted'))})}
async function persistCapture(){
 if(!pendingCapture||captureSaving)return;
 captureSaving=true;setSaveStatus('SAVING CAPTURE');
 const {file:f,context:ctx}=pendingCapture,pr=state.projects.find(x=>x.id===ctx.projectId);
 let h;for(const d of pr.days)for(const s of d.scenes)for(const u of s.setups){const found=u.shots.find(x=>x.id===ctx.shotId);if(found)h=found}
 if(!h){captureSaving=false;return toast('The shot is no longer available.')}
 const kind=f.type.startsWith('video/')?'video':'image',mediaId=uid(),entry={id:uid(),mediaId,kind,tag:'GENERAL',note:'',take:ctx.take,created:now()},record={id:mediaId,blob:f,name:f.name,type:f.type,...ctx,created:entry.created,kind};
 h.media.push(entry);
 try{
  try{await commitCapture(record)}catch(error){
   // Some WebKit storage contexts cannot prepare file-backed Blob records.
   // Retry the same atomic transaction with structured-clone bytes, preserving
   // both existing Blob records and the reference/media relationship.
   if(error?.name!=='UnknownError')throw error;
   const {blob,...meta}=record;
   await commitCapture({...meta,bytes:await f.arrayBuffer()});
  }
  pendingCapture=null;setSaveStatus('SAVED ON DEVICE');go('catalog',{mediaId:entry.id},route.page==='captureError');toast('Capture saved');
 }catch(error){
  console.error('Capture storage failed',error?.name,error?.message);
  h.media=h.media.filter(x=>x.id!==entry.id);setSaveStatus('CAPTURE NOT SAVED',true);go('captureError',{},route.page==='captureError');
 }finally{captureSaving=false}
}
function captureErrorScreen(){$('main').innerHTML=pageTop('Capture not saved',raw()?.code||'Shot')+'<p class="error">The device could not store this capture. Keep this screen open, free storage, then retry.</p><button class="primary action" onclick="persistCapture()">Retry save</button><button class="secondary action" onclick="dl(pendingCapture.file.name,pendingCapture.file)">Save file to device</button>'}
async function previewHTML(mediaId){const f=await get('media',mediaId);if(!f)return '<p class="error">Media file is unavailable on this device.</p>';const url=URL.createObjectURL(mediaBlob(f));objectURLs.push(url);return f.kind==='video'||f.type?.startsWith('video/')?'<video class="preview" src="'+url+'" controls playsinline></video>':f.kind==='voice'||f.type?.startsWith('audio/')?'<audio class="preview" src="'+url+'" controls></audio>':'<img class="preview" src="'+url+'" alt="Captured reference">'}
async function catalogScreen(){const entry=raw().media.find(x=>x.id===route.mediaId);if(!entry)return back();const current=route;const preview=await previewHTML(entry.mediaId);if(current!==route)return;$('main').innerHTML=pageTop('Capture saved',raw().code)+'<div class="saved-banner">✓ ON DEVICE · TAKE '+String(entry.take).padStart(2,'0')+'</div>'+preview+'<p class="helper">'+esc(new Date(entry.created).toLocaleString())+'</p>'+selectField('captureTag','Type',CAPTURE_TYPES,entry.tag,'onchange="catalogEdit(\'tag\',this.value)"')+'<div class="field"><label for="captureNote">Note</label><textarea id="captureNote" oninput="catalogEdit(\'note\',this.value)">'+esc(entry.note)+'</textarea></div><button class="primary" onclick="back()">Done</button>'}
async function catalogEdit(key,value){const entry=raw().media.find(x=>x.id===route.mediaId);entry[key]=value;await save()}
async function referencesScreen(){const current=route;let html=pageTop('References',raw().code);for(const m of raw().media.slice().reverse()){html+='<div class="section"><h2>'+pretty(m.tag)+'</h2><span>TAKE '+String(m.take).padStart(2,'0')+'</span></div>'+await previewHTML(m.mediaId)+'<p>'+esc(m.note)+'</p><button class="secondary" onclick="go(\'catalog\',{mediaId:\''+m.id+'\'})">Edit catalog</button>'}if(!raw().media.length)html+='<div class="empty">No references yet.</div>';if(current===route)$('main').innerHTML=html}
function measurementScreen(){route.captureTake=raw().take;$('main').innerHTML=pageTop('Measurement',raw().code)+'<p class="meta">TAKE '+String(route.captureTake).padStart(2,'0')+'</p><form onsubmit="saveMeasurement(event)">'+field('mf','From','','text','required')+field('mt','To','','text','required')+field('mv','Value','','number','required step="any"')+selectField('mu','Unit',['m','cm','mm','ft','in','deg'],'m')+selectField('mm','Source / method',['LASER','TAPE','MANUAL','PHONE_SENSOR','CALCULATED','ESTIMATED','OTHER'],'MANUAL','onchange="document.getElementById(\'methodCustom\').hidden=this.value!==\'OTHER\'"')+'<div id="methodCustom" hidden>'+field('mmCustom','Custom method')+'</div>'+selectField('mc','Confidence',['EXACT','MEASURED','APPROXIMATE','REFERENCE'],'MEASURED')+'<button class="primary action">Save measurement</button></form>'}
async function saveMeasurement(e){e.preventDefault();const value=Number($('mv').value),unit=$('mu').value,factor={m:1,cm:.01,mm:.001,ft:.3048,in:.0254,deg:Math.PI/180};if(!Number.isFinite(value))return;if($('mm').value==='OTHER'&&!$('mmCustom').value.trim())return toast('Enter the custom method.');raw().measurements.push({id:uid(),from:$('mf').value.trim(),to:$('mt').value.trim(),value,unit,si:{value:value*factor[unit],unit:unit==='deg'?'rad':'m'},method:$('mm').value==='OTHER'?$('mmCustom').value.trim():$('mm').value,confidence:$('mc').value,take:route.captureTake,created:now()});await save();back();toast('Measurement saved')}
function measurementsScreen(){$('main').innerHTML=pageTop('Measurements',raw().code)+(raw().measurements.length?raw().measurements.slice().reverse().map(m=>'<div class="note-item"><span class="meta">TAKE '+String(m.take).padStart(2,'0')+' · '+esc(pretty(m.method))+' / '+esc(pretty(m.confidence))+'</span><p>'+esc(m.from)+' → '+esc(m.to)+'</p><h2>'+esc(m.value)+' <small>'+esc(m.unit)+'</small></h2></div>').join(''):'<div class="empty">No measurements yet.</div>')+'<button class="primary action" onclick="go(\'measure\')">+ Add measurement</button>'}
async function legacyScreen(){const current=route;let html=pageTop('Previous captures',raw().code);for(const m of [...(raw().plates||[]),...(raw().voice||[])])html+='<p class="meta">'+esc(m.type||'Audio')+' · TAKE '+esc(m.take)+'</p>'+await previewHTML(m.mediaId);if(current===route)$('main').innerHTML=html}
function toolsScreen(){const list=[['screen','Screen assets','Green & blue · fullscreen, share, PNG'],['markers','Tracking markers','Cross, circle & checker · physical sizes'],['distortion','Lens distortion','Calibration image · fullscreen, share, PNG'],['scale','Scale references','Metric reference · print at actual size']];$('main').innerHTML='<section class="hero"><div class="eyebrow accent">ON-SET UTILITIES</div><h1>Built for<br>the real world.</h1><p class="lead">From a screen in the frame to a marker on the set.</p></section><div class="list">'+list.map(([id,t,s],i)=>row(t,s,"go('"+id+"')",'','<span class="tool-index">0'+(i+1)+'</span>')).join('')+'</div>'}
let screenSettings={color:'GREEN',pattern:'5POINT',aspect:'16:9',width:1920,height:1080},screenBlob=null;
function screenAssetScreen(){$('main').innerHTML=pageTop('Screen assets','Tools')+'<div class="asset-workspace"><section class="asset-controls">'+selectField('assetColor','Color',[['GREEN','Green'],['BLUE','Blue']],screenSettings.color,'onchange="screenSettings.color=this.value;drawAsset()"')+selectField('assetPattern','Pattern',[['NONE','None'],['4CORNERS','4 corners'],['5POINT','5 point'],['GRID','Grid']],screenSettings.pattern,'onchange="screenSettings.pattern=this.value;drawAsset()"')+selectField('assetAspect','Aspect',[['16:9','16:9'],['9:16','9:16'],['19.5:9','19.5:9'],['4:3','4:3'],['CUSTOM','Custom']],screenSettings.aspect,'onchange="screenSettings.aspect=this.value;document.getElementById(\'assetCustom\').hidden=this.value!==\'CUSTOM\';drawAsset()"')+'<div id="assetCustom" '+(screenSettings.aspect==='CUSTOM'?'':'hidden')+'>'+field('assetWidth','Width / px',screenSettings.width,'number','min="64" max="4096" step="1" onchange="screenSettings.width=Number(this.value);drawAsset()"')+field('assetHeight','Height / px',screenSettings.height,'number','min="64" max="4096" step="1" onchange="screenSettings.height=Number(this.value);drawAsset()"')+'</div></section><section class="asset-output"><div class="preview-wrap"><canvas id="assetCanvas" aria-label="Screen asset preview"></canvas></div><p class="helper" id="assetSize"></p><div class="button-stack"><button class="primary" onclick="fullscreenAsset()">Fullscreen</button><button class="secondary" onclick="shareAsset()">Share</button><button class="secondary" onclick="saveAsset()">Save PNG</button></div></section></div>';drawAsset()}
function drawAsset(){const c=$('assetCanvas');if(!c)return;let w,h;if(screenSettings.aspect==='CUSTOM'){w=screenSettings.width;h=screenSettings.height;if(!Number.isInteger(w)||!Number.isInteger(h)||w<64||h<64||w>4096||h>4096){$('assetSize').textContent='Use whole dimensions between 64 and 4096 px.';screenBlob=null;return}}else{const [a,b]=screenSettings.aspect.split(':').map(Number);w=a>=b?1920:Math.round(1920*a/b);h=a>=b?Math.round(1920*b/a):1920}c.width=w;c.height=h;const ctx=c.getContext('2d'),green=screenSettings.color==='GREEN';ctx.fillStyle=green?'#00b83c':'#0648e8';ctx.fillRect(0,0,w,h);ctx.strokeStyle=green?'#007c2a':'#12329a';ctx.lineWidth=Math.max(3,Math.min(w,h)*.006);const points=[],a=.13,b=.87;if(['4CORNERS','5POINT'].includes(screenSettings.pattern))points.push([a,a],[b,a],[a,b],[b,b]);if(screenSettings.pattern==='5POINT')points.push([.5,.5]);if(screenSettings.pattern==='GRID')for(let x=1;x<6;x++)for(let y=1;y<4;y++)points.push([x/6,y/4]);const len=Math.min(w,h)*.022;for(const [x,y] of points){ctx.beginPath();ctx.moveTo(w*x-len,h*y);ctx.lineTo(w*x+len,h*y);ctx.moveTo(w*x,h*y-len);ctx.lineTo(w*x,h*y+len);ctx.stroke()}$('assetSize').textContent=w+' × '+h+' px · chroma-family tracking points';const version=++assetVersion;screenBlob=null;c.toBlob(b=>{if(version===assetVersion)screenBlob=b},'image/png')}
let assetVersion=0;
function assetName(){return [p().code,shot()?.code,screenSettings.color,screenSettings.aspect==='CUSTOM'?screenSettings.width+'x'+screenSettings.height:screenSettings.aspect.replace(':','x'),screenSettings.pattern].filter(Boolean).join('_')+'.png'}
function saveAsset(){if(!screenBlob)return toast('Wait for a valid preview.');dl(assetName(),screenBlob)}
async function shareAsset(){if(!screenBlob)return toast('Wait for a valid preview.');const file=new File([screenBlob],assetName(),{type:'image/png'});try{if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:'SLYHIGH VFX Tools'});else{saveAsset();toast('Sharing unavailable. PNG saved instead.')}}catch(e){if(e.name!=='AbortError'){saveAsset();toast('PNG saved instead.')}}}
function fullscreenAsset(){if(screenBlob)showCanvasFullscreen($('assetCanvas'),screenSettings.color==='GREEN'?'#00b83c':'#0648e8')}
function closeFullscreen(){if(document.fullscreenElement)document.exitFullscreen?.().catch(()=>{});$('assetFullscreen')?.remove()}
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeFullscreen()});
const paperOptions=[['A4','A4 · 210 × 297 mm'],['Letter','Letter · 216 × 279 mm']];
function markerScreen(){$('main').innerHTML=pageTop('Tracking markers','Tools')+selectField('markerStyle','Style',[['cross','Cross'],['circle','Circle'],['checker','Checker']],'cross','onchange="markerPreview()"')+selectField('markerSize','Physical size',[['25','25 mm'],['50','50 mm'],['100','100 mm'],['200','200 mm']],'50','onchange="markerPreview()"')+selectField('markerPaper','Paper',paperOptions,'A4')+selectField('markerCount','Count',['1','4','8','12'],'4')+'<div class="preview-wrap" id="markerPreview"></div><p class="helper">Print at 100% / actual size. Disable fit-to-page. IDs are reserved when you prepare a sheet.</p><button class="primary action" onclick="printMarkers()">Print / Save PDF</button>';markerPreview()}
function markerSVG(style){let shape=style==='cross'?'<path d="M40 0h20v40h40v20H60v40H40V60H0V40h40z" fill="black" stroke="none"/>':style==='circle'?'<circle cx="50" cy="50" r="46" stroke="black" stroke-width="8" fill="white"/><circle cx="50" cy="50" r="10" fill="black" stroke="none"/>':'<rect width="100" height="100" fill="white" stroke="none"/><path d="M0 0h50v50H0zM50 50h50v50H50z" fill="black" stroke="none"/>';return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100%" height="100%">'+shape+'</svg>'}
function markerPreview(){$('markerPreview').innerHTML='<div style="background:white;padding:20px;width:170px;height:170px">'+markerSVG($('markerStyle').value)+'</div>'}
function preparePrint(html,paper='A4',margin=10,title){$('printRoot').innerHTML='<style>@page{size:'+paper+';margin:'+margin+'mm}</style>'+html;if(title)document.title=title;window.print()}
async function printMarkers(){const count=Number($('markerCount').value),size=Number($('markerSize').value),style=$('markerStyle').value,paper=$('markerPaper').value,signature=[count,size,style,paper].join('|');if(route.markerSignature!==signature){const start=p().nextMarkerId||1;p().nextMarkerId=start+count;route.markerStart=start;route.markerSignature=signature;await save()}const width=paper==='A4'?210:215.9,height=paper==='A4'?297:279.4,cols=Math.max(1,Math.floor((width-10+8)/(size+8))),rows=Math.max(1,Math.floor((height-10+8)/(size+22))),per=cols*rows;let pages=[];for(let start=0;start<count;start+=per){let items=[];for(let i=start;i<Math.min(start+per,count);i++){let id=p().code+'-TRK-'+String(route.markerStart+i).padStart(3,'0');items.push('<div class="print-marker" style="width:'+size+'mm"><div style="width:'+size+'mm;height:'+size+'mm">'+markerSVG(style)+'</div><div class="print-label">'+esc(id)+' · '+size+' mm</div></div>')}pages.push('<section class="marker-sheet '+(start+per<count?'print-page':'')+'">'+items.join('')+'</section>')}preparePrint(pages.join(''),paper,5)}
function distortionSVG(){let lines='';for(let x=0;x<=180;x+=10)lines+='<path d="M'+x+' 0V240"/>';for(let y=0;y<=240;y+=10)lines+='<path d="M0 '+y+'H180"/>';return '<svg xmlns="http://www.w3.org/2000/svg" class="print-grid" viewBox="0 0 180 240"><rect width="180" height="240" fill="white" stroke="none"/><g stroke="black" stroke-width=".55">'+lines+'</g><path d="M80 120h20M90 110v20" stroke="black" stroke-width="1.5"/><circle cx="90" cy="120" r="5" fill="white" stroke="black" stroke-width=".75"/><path d="M87 120h6M90 117v6" stroke="black" stroke-width=".8"/></svg>'}
function distortionScreen(){
 const c=raw()?.camera||{};
 $('main').innerHTML=pageTop('Lens distortion','Tools')+'<div class="asset-workspace"><section class="asset-controls"><p class="helper">A square-cell calibration grid with a center crosshair. Save or share it as an image.</p>'+selectField('gridAspect','Aspect',[['16:9','16:9'],['9:16','9:16'],['4:3','4:3'],['1:1','1:1'],['CUSTOM','Custom']],gridSettings.aspect,'onchange="gridSettings.aspect=this.value;document.getElementById(\'gridCustom\').hidden=this.value!==\'CUSTOM\';drawDistortion()"')+'<div id="gridCustom" '+(gridSettings.aspect==='CUSTOM'?'':'hidden')+'>'+field('gridWidth','Width / px',gridSettings.width,'number','min="64" max="4096" step="1" onchange="gridSettings.width=Number(this.value);drawDistortion()"')+field('gridHeight','Height / px',gridSettings.height,'number','min="64" max="4096" step="1" onchange="gridSettings.height=Number(this.value);drawDistortion()"')+'</div>'+selectField('gridDensity','Grid density',[['12','12 cells across short side'],['18','18 cells across short side'],['24','24 cells across short side']],gridSettings.density,'onchange="gridSettings.density=Number(this.value);drawDistortion()"')+'<div class="settings">'+[['Camera',cam(c.cameraId)],['Lens',lens(c.lensId)],['Focal',c.focal!=null?c.focal+' mm':'—'],['Focus',c.focus!=null?c.focus+' m':'—'],['Sensor mode',c.sensorMode||'—']].map(([k,v])=>'<div class="setting"><label>'+k+'</label><span style="max-width:65%;text-align:right">'+esc(v)+'</span></div>').join('')+'</div></section><section class="asset-output"><div class="preview-wrap"><canvas id="gridCanvas" aria-label="Lens distortion grid preview"></canvas></div><p class="helper" id="gridSize"></p><div class="button-stack"><button class="primary" onclick="fullscreenGrid()">Fullscreen</button><button class="secondary" onclick="shareGrid()">Share</button><button class="secondary" onclick="saveGrid()">Save PNG</button></div></section></div>';drawDistortion();
}
function printDistortion(){const c=raw()?.camera||{},paper=$('gridPaper').value;preparePrint('<div class="print-label">SLYHIGH VFX Tools · '+esc(p().code)+' / '+esc(shot()?.code||'')+'<br>'+esc(cam(c.cameraId))+' · '+esc(lens(c.lensId))+'<br>Focal '+esc(c.focal??'—')+' mm · Focus '+esc(c.focus??'—')+' m · Sensor '+esc(c.sensorMode||'—')+'</div><div style="width:170mm;height:226.67mm">'+distortionSVG()+'</div>',paper,10)}
function scaleScreen(){$('main').innerHTML=pageTop('Scale references','Tools')+'<p class="helper">100 mm reference with 10 mm divisions. Verify with a physical ruler after printing.</p>'+selectField('scalePaper','Paper',paperOptions,'A4')+'<div class="preview-wrap" style="padding:20px">'+scaleSVG()+'</div><button class="primary action" onclick="printScale()">Print / Save PDF</button>'}
function scaleSVG(){return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 110 35"><rect width="110" height="35" fill="white" stroke="none"/>'+Array.from({length:10},(_,i)=>'<rect x="'+(5+i*10)+'" y="8" width="10" height="10" fill="'+(i%2?'white':'black')+'" stroke="black" stroke-width=".3"/>').join('')+'<path d="M5 5v18M105 5v18" stroke="black" stroke-width=".3"/><text x="55" y="29" text-anchor="middle" fill="black" stroke="none" font-family="Arial" font-size="5">100 mm</text></svg>'}
function printScale(){preparePrint('<h2>SLYHIGH VFX Tools · Scale reference</h2><p>'+esc(p().code)+' · Print at actual size / 100%.</p><div style="width:110mm;height:35mm">'+scaleSVG()+'</div>',$('scalePaper').value)}
function exportScreen(){$('main').innerHTML='<section class="hero"><div class="eyebrow accent">'+esc(p().code)+' / EXPORT</div><h1>Ready for<br>post.</h1><p class="lead">Structured data. The full context.</p></section><div class="list">'+row('Project report / PDF','All '+shots().length+' shots · camera states, notes & measurements',"report('project')")+row('Project JSON','Full structured project metadata',"exportJSON()")+row('Shot CSV','Camera states & acquisition counts',"exportCSV()")+row('Project backup','Metadata + original media in one file',"exportBackup()")+(shot()?row('Current shot / PDF',shot().code+' only',"report('shot')"):'')+'</div><p class="footer-note">slyhigh.vfxdata / '+VER+'<br>JSON and CSV contain metadata. Use project backup to include original photos and videos.</p>'}
function report(scope='project'){
 const all=scope==='shot'?(shot()?[shot()]:[]):shots();if(!all.length)return toast('Create a shot before exporting a report.');
 const header='<div class="report-heading"><h1>'+esc(p().name)+'</h1><p>SLYHIGH VFX Tools · '+esc(p().code)+' · '+all.length+' shot'+(all.length===1?'':'s')+'</p><p>Operator: '+esc(state.operator||'—')+' · '+esc(new Date().toLocaleString())+'</p></div>';
 preparePrint(header+all.map(reportShotHTML).join(''),'A4',12,p().code+'_'+(scope==='shot'?all[0].code:'ALL_SHOTS')+'_VFX_REPORT');
}
async function exportBackup(){toast('Preparing backup with original media…');const data=payload(),all=shots(data.project),ids=[...new Set(all.flatMap(h=>[...(h.media||[]),...(h.plates||[]),...(h.voice||[])].map(m=>m.mediaId)).filter(Boolean))];const media=[];for(const id of ids){const entry=await get('media',id);if(!entry){toast('Backup stopped: a media file is missing.');return}const encoded=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(mediaBlob(entry))});const {blob,bytes,...meta}=entry;media.push({...meta,data:encoded})}dl(data.project.code+'_VFX_BACKUP.json',new Blob([JSON.stringify({...data,backup_format:'slyhigh.media-backup.1',media})],{type:'application/json'}));toast('Backup ready')}
window.addEventListener('unhandledrejection',e=>{console.error(e.reason);setSaveStatus('ACTION FAILED · RETRY',true)});
async function init(){try{await openDB();await load();state.projects||=[];for(const pr of state.projects){pr.cameras||=[];pr.lenses||=[];pr.days||=[];for(const h of shots(pr)){// Fill absent collections on the stored object without replacing existing data.
for(const d of pr.days)for(const s of d.scenes)for(const u of s.setups){const r=u.shots.find(x=>x.id===h.id);if(r){for(const k of ['types','media','measurements','notes','plates','voice'])r[k]||=[];r.camera||={};r.take||=1}}}}
route={page:p()?(shot()?'shot':'shoot'):'projects',projectId:state.activeProjectId,shotId:state.activeShotId};history.replaceState({sly:true},'');if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render();setSaveStatus('ON DEVICE');if(navigator.storage?.persist)navigator.storage.persist().catch(()=>{});window.visualViewport?.addEventListener('resize',()=>document.body.classList.toggle('keyboard',window.visualViewport.height<window.innerHeight*.75))}catch(e){$('main').innerHTML='<section class="hero"><h1>Storage unavailable.</h1><p class="lead">Allow browser storage, then reload to open your projects.</p><button class="primary action" onclick="location.reload()">Retry</button></section>';console.error(e)}}init();


function renderCaptureDock(){let dock=$('captureDock');if(!dock){dock=document.createElement('div');dock.id='captureDock';document.body.append(dock)}const show=route.page==='shot'&&raw();document.body.classList.toggle('has-capture-dock',!!show);dock.hidden=!show;if(show)dock.innerHTML='<span><small>CURRENT TAKE</small><b>'+String(raw().take||1).padStart(2,'0')+'</b></span><button class="primary" onclick="capture()">'+icon('camera')+' Capture photo / video</button>'}

function localDate(){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)}
function ensureSetup(pr,date,scene,setup){let d=pr.days.find(x=>x.date===date);if(!d){const n=Math.max(0,...pr.days.map(x=>Number(x.code.replace(/\D/g,''))||0))+1;d={id:uid(),code:'DAY '+String(n).padStart(2,'0'),date,scenes:[]};pr.days.push(d)}let s=d.scenes.find(x=>x.code===scene);if(!s){s={id:uid(),code:scene,setups:[]};d.scenes.push(s)}let u=s.setups.find(x=>x.code===setup);if(!u){u={id:uid(),code:setup,shots:[]};s.setups.push(u)}return u}
async function updateShotDate(date){if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return;const h=shot(),r=raw();if(date===h._d.date)return;const target=ensureSetup(p(),date,h._s.code,h._u.code);h._u.shots=h._u.shots.filter(x=>x.id!==r.id);target.shots.push(r);for(const d of p().days){for(const s of d.scenes)s.setups=s.setups.filter(u=>u.shots.length);d.scenes=d.scenes.filter(s=>s.setups.length)}p().days=p().days.filter(d=>d.scenes.length);await save();render();toast('Shoot date updated')}
function slateHeader(h,r){return '<section class="slate" aria-label="Shot slate"><div class="slate-production"><span class="eyebrow">PRODUCTION</span><b>'+esc(p().name)+'</b><span class="meta">'+esc(p().code)+'</span></div><div class="slate-grid"><div class="slate-shot"><span class="eyebrow">SHOT</span><h1>'+esc(h.code)+'</h1></div><div class="slate-cell"><span class="eyebrow">SCENE</span><strong>'+esc(h._s.code)+'</strong></div><div class="slate-cell"><span class="eyebrow">SETUP</span><strong>'+esc(h._u.code)+'</strong></div><div class="slate-take"><span class="eyebrow accent">CURRENT TAKE</span><div class="take-controls"><button id="takeMinus" aria-label="Previous take" onclick="take(-1)" '+(r.take<=1?'disabled':'')+'>−</button><strong id="takeNumber" aria-live="polite">'+String(r.take||1).padStart(2,'0')+'</strong><button aria-label="Next take" onclick="take(1)">+</button></div></div></div></section>'}
function shotTypeFields(types=[]){return [...types,''].map((v,i)=>selectField('shotType_'+i,i===0?'Shot type':i<types.length?'Additional type':'Add another type',[['',''],...TYPES.map(t=>[t,pretty(t)])],v,'onchange="changeShotType('+i+',this.value)"')).join('')}
async function changeShotType(index,value){const isNew=route.page==='newShot',types=[...(isNew?route.newTypes:raw().types)];if(value&&types.some((t,i)=>i!==index&&t===value)){toast('This type is already selected.')}else{if(value)types[index]=value;else types.splice(index,1);if(isNew)route.newTypes=types;else{raw().types=types;await save()}}$('shotTypes').innerHTML=shotTypeFields(isNew?route.newTypes:raw().types)}
const SHUTTER_ANGLES=[360,180,172.8,144,90,45],SHUTTER_FRACTIONS=[24,25,30,47.952,48,50,60,96,100,120,125,250,500,1000,2000];
const compactNumber=v=>v==null?'':Number(Number(v).toFixed(6)).toString();
function syncShutter(c){const fps=Number(c.fps);if(!(fps>0)){if(c.shutterMode==='fraction')c.shutter=null;else c.shutterFraction=null;return}if(c.shutterMode==='fraction')c.shutter=c.shutterFraction>0?360*fps/c.shutterFraction:null;else c.shutterFraction=c.shutter>0?360*fps/c.shutter:null}
function shutterControls(){const c=raw().camera||{},fraction=c.shutterMode==='fraction',value=fraction?c.shutterFraction:c.shutter,presets=fraction?SHUTTER_FRACTIONS:SHUTTER_ANGLES,known=presets.find(v=>Math.abs(v-value)<1e-8),selected=value==null?'':known!==undefined?String(known):'custom';return '<div class="shutter-head"><label for="shutterValue">Shutter<small>'+provenance(raw(),fraction?'shutterFraction':'shutter')+'</small></label><div class="segmented" aria-label="Shutter representation"><button type="button" aria-pressed="'+!fraction+'" onclick="setShutterMode(\'angle\')">Angle °</button><button type="button" aria-pressed="'+fraction+'" onclick="setShutterMode(\'fraction\')">Fraction 1/s</button></div></div><div class="field shutter-value"><select id="shutterValue" aria-label="Shutter value" onchange="selectShutter(this.value)">'+opt('','',selected)+presets.map(v=>opt(v,fraction?'1/'+v+' s':v+'°',selected)).join('')+opt('custom','Custom',selected)+'</select></div><div id="shutterCustomWrap" '+(selected==='custom'?'':'hidden')+'>'+field('shutterCustom',fraction?'Denominator · exposure is 1 / value seconds':'Angle / degrees',selected==='custom'?compactNumber(value):'','number','min="0.000001" step="any" onchange="updateShutter(this.value)"')+'</div><p class="helper shutter-helper" id="shutterEquivalent">'+shutterEquivalent(c)+'</p>'}
function shutterEquivalent(c){if(!(Number(c.fps)>0))return 'Set FPS to calculate the equivalent angle or fraction.';if(c.shutterMode==='fraction'&&c.shutterFraction>0)return 'Equivalent '+compactNumber(c.shutter)+'° at '+c.fps+' fps';if(c.shutter>0)return 'Equivalent 1/'+compactNumber(360*c.fps/c.shutter)+' s at '+c.fps+' fps';return 'Choose a shutter value.'}
async function setShutterMode(mode){const c=raw().camera,current=c.shutterMode==='fraction'?c.shutterFraction:c.shutter;if(mode!==(c.shutterMode||'angle')&&current>0&&!(Number(c.fps)>0))return toast('Set FPS before converting shutter units.');syncShutter(c);c.shutterMode=mode;syncShutter(c);$('shutterControl').innerHTML=shutterControls();await save()}
async function selectShutter(v){if(v==='custom'){$('shutterCustomWrap').hidden=false;$('shutterCustom').focus();return}await updateShutter(v);$('shutterControl').innerHTML=shutterControls()}
async function updateShutter(value){const h=raw(),c=h.camera,fraction=c.shutterMode==='fraction',n=value===''?null:Number(value);if(n!==null&&(!Number.isFinite(n)||n<=0||(!fraction&&n>360)))return toast(fraction?'Enter a positive denominator.':'Use an angle greater than 0 and up to 360°.');c[fraction?'shutterFraction':'shutter']=n;h.cameraProvenance||={};h.cameraProvenance.shutter=h.cameraProvenance.shutterFraction=n===null?'EMPTY':'USER ENTERED';syncShutter(c);c.updated=now();await save();$('shutterEquivalent').textContent=shutterEquivalent(c)}
const navObserver=new ResizeObserver(()=>{if(!$('nav').hidden)document.documentElement.style.setProperty('--nav-height',$('nav').getBoundingClientRect().height+'px')});navObserver.observe($('nav'));

let gridSettings={aspect:'16:9',width:3840,height:2160,density:18},gridBlob=null,gridVersion=0;
function drawDistortion(){const canvas=$('gridCanvas');if(!canvas)return;let w=gridSettings.width,h=gridSettings.height;if(gridSettings.aspect!=='CUSTOM'){const [a,b]=gridSettings.aspect.split(':').map(Number);w=a>=b?3840:Math.round(3840*a/b);h=a>=b?Math.round(3840*b/a):3840}const version=++gridVersion;gridBlob=null;if(!Number.isInteger(w)||!Number.isInteger(h)||w<64||h<64||w>4096||h>4096){$('gridSize').textContent='Use whole dimensions from 64 to 4096 px.';return}canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d'),step=Math.min(w,h)/gridSettings.density;ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#000';ctx.lineWidth=Math.max(1,Math.min(w,h)/700);ctx.beginPath();for(let i=-Math.ceil(w/step/2);i<=Math.ceil(w/step/2);i++){const x=w/2+i*step;ctx.moveTo(x,0);ctx.lineTo(x,h)}for(let i=-Math.ceil(h/step/2);i<=Math.ceil(h/step/2);i++){const y=h/2+i*step;ctx.moveTo(0,y);ctx.lineTo(w,y)}ctx.stroke();ctx.lineWidth*=3;ctx.beginPath();ctx.arc(w/2,h/2,step*.28,0,Math.PI*2);ctx.moveTo(w/2-step*.5,h/2);ctx.lineTo(w/2+step*.5,h/2);ctx.moveTo(w/2,h/2-step*.5);ctx.lineTo(w/2,h/2+step*.5);ctx.stroke();$('gridSize').textContent=w+' × '+h+' px · square cells · center crosshair';canvas.toBlob(b=>{if(version===gridVersion)gridBlob=b},'image/png')}
function gridName(){const c=raw()?.camera||{},canvas=$('gridCanvas');return [p().code,shot()?.code,'DISTORTION',c.focal!=null?'F'+compactNumber(c.focal)+'mm':null,canvas.width+'x'+canvas.height].filter(Boolean).join('_')+'.png'}
function saveGrid(){if(!gridBlob)return toast('Wait for a valid grid preview.');dl(gridName(),gridBlob)}
async function shareGrid(){if(!gridBlob)return toast('Wait for a valid grid preview.');const file=new File([gridBlob],gridName(),{type:'image/png'});try{if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:'SLYHIGH lens distortion grid'});else{saveGrid();toast('Sharing unavailable. PNG saved instead.')}}catch(e){if(e.name!=='AbortError'){saveGrid();toast('PNG saved instead.')}}}
function fullscreenGrid(){if(gridBlob)showCanvasFullscreen($('gridCanvas'),'#fff')}
function showCanvasFullscreen(source,background){const overlay=document.createElement('div');overlay.className='full-asset';overlay.style.background=background;overlay.id='assetFullscreen';const canvas=document.createElement('canvas');canvas.width=source.width;canvas.height=source.height;canvas.getContext('2d').drawImage(source,0,0);overlay.append(canvas);const exit=document.createElement('button');exit.textContent='Exit fullscreen';exit.onclick=closeFullscreen;overlay.append(exit);document.body.append(overlay);overlay.requestFullscreen?.().catch(()=>{});exit.focus()}
function shutterSeconds(c){if(c.shutterMode==='fraction')return c.shutterFraction>0?1/c.shutterFraction:null;return c.shutter>0&&c.fps>0?c.shutter/(360*c.fps):null}
function reportShotHTML(h){const c=h.camera||{},labels={focal:'Focal / mm',focus:'Focus / m',aperture:'T / F stop',ei:'EI / ISO',wb:'White balance / K',fps:'FPS',nd:'ND',movement:'Movement',sensorMode:'Sensor mode',color:'Color / gamma'},shutter=c.shutterMode==='fraction'?(c.shutterFraction?'1/'+compactNumber(c.shutterFraction)+' s':'—'):(c.shutter!=null?compactNumber(c.shutter)+'°':'—');return '<section class="report-shot" data-shot-id="'+esc(h.id)+'"><h2>'+esc(h.code)+'</h2><p>'+esc(h._d.date)+' · SC '+esc(h._s.code)+' · SETUP '+esc(h._u.code)+' · TAKE '+esc(h.take)+'</p><p>'+h.types.map(t=>esc(pretty(t))).join(' · ')+'</p><table><tr><th>Camera</th><td>'+esc(cam(c.cameraId))+'</td></tr><tr><th>Lens</th><td>'+esc(lens(c.lensId))+'</td></tr>'+Object.entries(labels).map(([k,l])=>'<tr><th>'+l+'</th><td>'+esc(c[k]??'—')+'</td></tr>').join('')+'<tr><th>Shutter</th><td>'+esc(shutter)+'</td></tr></table><h3>Measurements</h3>'+(h.measurements.length?'<table>'+h.measurements.map(m=>'<tr><td>Take '+esc(m.take)+'</td><td>'+esc(m.from)+' → '+esc(m.to)+'</td><td>'+esc(m.value)+' '+esc(m.unit)+'</td><td>'+esc(m.method)+' / '+esc(m.confidence)+'</td></tr>').join('')+'</table>':'<p>None recorded.</p>')+'<h3>Notes</h3>'+(h.notes.map(n=>'<p><b>TAKE '+esc(n.take)+'</b> '+esc(n.text)+'</p>').join('')||'<p>None recorded.</p>')+'<h3>References</h3>'+(h.media.map(m=>'<p>TAKE '+esc(m.take)+' · '+esc(m.tag)+' · '+esc(m.note)+'</p>').join('')||'<p>None recorded.</p>')+'</section>'}
window.addEventListener('afterprint',()=>{document.title='SLYHIGH VFX Tools'});
