// Optional setup.attachments records share the existing atomic media/kv storage.
let attachmentBusy=false,attachmentContext=null,preparedPackage=null,packageBusy=false;
const shotFiles=h=>[...(h.media||[]),...(h.plates||[]),...(h.voice||[]),...(h.attachments||[])];
function fileSize(bytes=0){if(bytes<1024)return bytes+' B';const i=Math.min(3,Math.floor(Math.log(bytes)/Math.log(1024)));return (bytes/1024**i).toFixed(1)+' '+['B','KB','MB','GB'][i]}
function projectSetups(pr=p()){return (pr?.days||[]).flatMap(d=>d.scenes.flatMap(s=>s.setups.map(u=>({setup:u,day:d,scene:s}))))}
function findSetup(data,ctx){const pr=data.projects.find(x=>x.id===ctx.projectId);return pr?projectSetups(pr).find(x=>x.setup.id===ctx.setupId)?.setup:undefined}
function activeSetup(){return projectSetups().find(x=>x.setup.id===(route.setupId||shot()?._u.id))}
function setupLabel(x){return x.day.date+' · '+t('Scene')+' '+(x.scene.code||'—')+' · Setup '+(x.setup.code||'—')}
function projectFiles(pr){return [...shots(pr).flatMap(shotFiles),...projectSetups(pr).flatMap(x=>x.setup.attachments||[])]}
function setupsScreen(){$('main').innerHTML=pageTop(t('Setups & files'),p().name)+'<p class="helper">'+t('Files belong to a setup and are shared by its shots.')+'</p><div class="list">'+projectSetups().map(x=>row(setupLabel(x),x.setup.shots.length+' shots',"go('attachments',{setupId:'"+x.setup.id+"'})",(x.setup.attachments||[]).length+' '+t('files'))).join('')+'</div>'}
function attachmentsScreen(){const info=activeSetup(),h=info?.setup;if(!h)return go('shoot',{},true);$('main').innerHTML=pageTop(t('Files & LiDAR'),t('Setup'))+'<p class="setup-context">'+esc(setupLabel(info))+'</p><p class="helper">'+t('Files belong to a setup and are shared by its shots.')+'</p>'+'<p class="helper">'+t('Add any file format. For scans with textures or companion files, select them all or attach the scanner’s ZIP.')+'</p><button class="primary action" onclick="pickAttachments()">'+t('+ Add files')+'</button><p class="helper">'+t('Saved on this device. Export the delivery ZIP to share the originals with the report.')+'</p>'+section(t('Attached files'),(h.attachments||[]).length)+'<div class="attachment-list">'+((h.attachments||[]).map(a=>'<article class="attachment-card"><b>'+esc(a.name)+'</b><p class="meta">'+fileSize(a.size)+'</p><div class="row"><button class="secondary" onclick="prepareAttachment(\''+a.id+'\')">'+t('Save file')+'</button><button class="danger-button" onclick="confirmAttachmentDelete(\''+a.id+'\')">'+t('Delete')+'</button></div></article>').join('')||'<p class="empty">'+t('No files attached yet.')+'</p>')+'</div>'}
function pickAttachments(){if(attachmentBusy||captureSaving||pendingCapture)return toast(t('Finish saving the capture before adding files.'));const h=activeSetup()?.setup;if(!h)return;attachmentContext={projectId:p().id,setupId:h.id};$('attachmentInput').value='';$('attachmentInput').click()}
function taskDialog(label){$('dlgBody').innerHTML='<h2>'+t(label)+'</h2><p id="fileProgress" role="status">'+t('Keep this screen open until it finishes.')+'</p>';if(!$('dlg').open)$('dlg').showModal()}
function fileTaskError(message){$('dlgBody').innerHTML='<h2>'+t('Files not saved')+'</h2><p>'+esc(message)+'</p><button class="secondary" onclick="closeDlg()">'+t('Close')+'</button>';if(!$('dlg').open)$('dlg').showModal()}
function commitFileState(next,records=[],remove=[]){return new Promise((resolve,reject)=>{let tx;try{tx=db.transaction(['media','kv'],'readwrite');tx.oncomplete=resolve;tx.onerror=e=>reject(tx.error||e.target.error);tx.onabort=()=>reject(tx.error||new Error('Storage transaction aborted'));const os=tx.objectStore('media');for(const entry of records)os.put(entry);for(const id of remove)os.delete(id);tx.objectStore('kv').put(next,'state')}catch(e){try{tx?.abort()}catch{}reject(e)}})}
async function addAttachments(files,ctx=attachmentContext){
 if(!files.length||!ctx||attachmentBusy||captureSaving)return;
 attachmentBusy=true;taskDialog('Saving files…');
 try{
  if(!findSetup(state,ctx))throw Error(t('The setup is no longer available.'));
  const total=files.reduce((n,f)=>n+f.size,0),estimate=await navigator.storage?.estimate?.().catch(()=>null);
  if(estimate?.quota&&total>estimate.quota-(estimate.usage||0))throw Error(t('Not enough device storage. Free space and select the files again.'));
  const records=files.map(f=>({id:uid(),blob:f,name:f.name,type:f.type||'application/octet-stream',size:f.size,lastModified:f.lastModified,kind:'attachment',created:now(),...ctx}));
  const next=structuredClone(state),h=findSetup(next,ctx);if(!h)throw Error(t('The setup is no longer available.'));h.attachments||=[];
  for(const f of records)h.attachments.push({id:uid(),mediaId:f.id,name:f.name,size:f.size,mime:f.type,lastModified:f.lastModified,kind:'attachment',created:f.created});
  try{await commitFileState(next,records)}catch(e){
   // Older WebKit may reject file-backed Blobs. Retry atomically as bytes.
   if(!['UnknownError','DataCloneError'].includes(e.name))throw e;
   const fallback=[];for(const r of records){const {blob,...meta}=r;fallback.push({...meta,bytes:await blob.arrayBuffer()})}await commitFileState(next,fallback);
  }
  state=next;clearPreparedPackage();clearPreparedPDF();closeDlg();render();setSaveStatus(t('SAVED ON DEVICE'));toast(t('Files saved'));
 }catch(e){fileTaskError(e.name==='QuotaExceededError'?t('Not enough device storage. Free space and select the files again.'):t('Could not save these files. Nothing was added. Select them again to retry.')+' '+e.message)}finally{attachmentBusy=false;$('attachmentInput').value=''}
}
async function prepareAttachment(id){const a=activeSetup()?.setup.attachments?.find(x=>x.id===id);if(!a)return;try{const entry=await get('media',a.mediaId);if(!entry)throw Error();const url=URL.createObjectURL(mediaBlob(entry));objectURLs.push(url);$('dlgBody').innerHTML='<h2>'+t('Save file')+'</h2><p class="pdf-filename">'+esc(a.name)+'</p><a class="primary" download="'+esc(a.name)+'" href="'+url+'">'+t('Save file')+'</a><button class="secondary action" onclick="closeDlg()">'+t('Close')+'</button>';$('dlg').showModal()}catch{toast(t('Media file is unavailable on this device.'))}}
function confirmAttachmentDelete(id){const a=activeSetup()?.setup.attachments?.find(x=>x.id===id);if(!a||attachmentBusy)return;const ctx={projectId:p().id,setupId:activeSetup().setup.id};$('dlgBody').innerHTML='<h2>'+t('Delete file?')+'</h2><p class="pdf-filename">'+esc(a.name)+'</p><p>'+t('This removes the file for all shots in this setup. The shots remain.')+'</p><div class="row"><button onclick="closeDlg()">'+t('Cancel')+'</button><button id="deleteAttachment" class="danger-fill">'+t('Delete')+'</button></div>';$('deleteAttachment').onclick=()=>deleteAttachment(ctx,id);$('dlg').showModal()}
async function deleteAttachment(ctx,id){if(attachmentBusy)return;attachmentBusy=true;try{const next=structuredClone(state),h=findSetup(next,ctx),a=h?.attachments?.find(x=>x.id===id);if(!a)return;h.attachments=h.attachments.filter(x=>x.id!==id);const shared=next.projects.some(pr=>projectFiles(pr).some(x=>x.mediaId===a.mediaId));await commitFileState(next,[],shared?[]:[a.mediaId]);state=next;clearPreparedPackage();clearPreparedPDF();closeDlg();render();toast(t('File deleted'))}catch{toast(t('Could not delete the file. Please retry.'))}finally{attachmentBusy=false}}
$('attachmentInput').addEventListener('change',e=>addAttachments([...e.target.files]));
$('dlg').addEventListener('cancel',e=>{if(attachmentBusy||packageBusy)e.preventDefault()});

// Safe, deterministic ZIP paths; preserve companion filenames unless they collide.
function archivePart(name){let s=String(name||'file').normalize('NFC').replace(/[<>:"/\\|?*\x00-\x1f\x7f]/g,'_').replace(/[. ]+$/g,'').slice(0,180);if(!s||s==='.'||s==='..')s='file';if(/^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/i.test(s))s='_'+s;return s}
function archiveUnique(name,used){const safe=archivePart(name),at=safe.lastIndexOf('.'),base=at>0?safe.slice(0,at):safe,ext=at>0?safe.slice(at):'';let value=safe,n=2;while(used.has(value.toLowerCase()))value=base+' ('+(n++)+')'+ext;used.add(value.toLowerCase());return value}
function packagePlan(all,project){const result=[];const groupsUsed=new Set();for(const x of projectSetups(project)){const label=[x.day.date,'SC_'+(x.scene.code||'unset'),'SETUP_'+(x.setup.code||'unset')].join('_'),folder='setups/'+archiveUnique(label,groupsUsed),used=new Set();for(const a of x.setup.attachments||[])result.push({setupId:x.setup.id,setup:setupLabel(x),group:'attachments',record:a,folder,used})}for(let i=0;i<all.length;i++){const h=all[i],folder='shots/'+String(i+1).padStart(3,'0')+'_'+archivePart(h.code),groups=[['attachments',h.attachments||[]],['references',h.media||[]],['plates',h.plates||[]],['audio',h.voice||[]]];for(const [group,items] of groups){const used=new Set();for(const a of items)result.push({shotId:h.id,shot:h.code,group,record:a,folder:folder+'/'+group,used})}}return result}
function clearPreparedPackage(){if(preparedPackage)URL.revokeObjectURL(preparedPackage.url);preparedPackage=null}
function packageReadyScreen(){if(!preparedPackage||preparedPackage.projectId!==p()?.id)return go('export',{},true);const f=preparedPackage.file;$('main').innerHTML=pageTop(t('Delivery ready'),t('Export'))+'<p>'+t('Includes the PDF, project data, scans by setup and references by shot.')+'</p><p class="pdf-filename">'+esc(f.name)+'</p><p class="helper">'+fileSize(f.size)+'</p><div class="button-stack pdf-actions"><a id="savePackage" class="primary" href="'+preparedPackage.url+'" download="'+esc(f.name)+'">'+t('Save ZIP')+'</a>'+(navigator.canShare?.({files:[f]})?'<button class="secondary" onclick="sharePackage()">'+t('Share ZIP')+'</button>':'')+'</div>'+(preparedPackage.warnings?'<p class="helper">'+t('Some images could not be previewed in the PDF. Their original files are included in the ZIP.')+'</p>':'')}
async function sharePackage(){if(!preparedPackage)return;try{await navigator.share({files:[preparedPackage.file],title:preparedPackage.file.name})}catch(e){if(e.name!=='AbortError')toast(t('Could not share. Use Save ZIP.'))}}
async function exportPackage(){
 if(packageBusy||attachmentBusy||captureSaving)return;
 const data=payload(),all=shots(data.project);if(!all.length&&!projectFiles(data.project).length)return toast(t('Create a shot before exporting a report.'));
 packageBusy=true;clearPreparedPackage();taskDialog('Preparing delivery…');const origin=route,language=currentLanguage(),created=new Date();
 try{
  const plan=packagePlan(all,data.project),entries=[],inventory=[];
  for(let i=0;i<plan.length;i++){const item=plan[i],a=item.record,stored=await get('media',a.mediaId);if(!stored||(!(stored.blob instanceof Blob)&&!(stored.bytes instanceof ArrayBuffer)))throw Error(t('Delivery stopped: a file is missing.')+' '+(item.setup||item.shot)+' / '+(a.name||a.mediaId));const blob=mediaBlob(stored),name=a.name||stored.name||a.mediaId,path=item.folder+'/'+archiveUnique(name,item.used);entries.push({path,blob,date:new Date(stored.lastModified||stored.created||created)});inventory.push({setupId:item.setupId,setup:item.setup,shotId:item.shotId,shot:item.shot,group:item.group,mediaId:a.mediaId,originalName:name,path,size:blob.size,type:stored.type,take:a.take});$('fileProgress').textContent=t('Preparing delivery…')+' '+(i+1)+' / '+plan.length}
  const reportName=pdfTitle('report',data.project)+'.pdf',result=await buildReportPDF({project:data.project,all,operator:data.operator,language,created,title:reportName.slice(0,-4),inventory});
  entries.unshift({path:reportName,blob:new Blob([result.bytes],{type:'application/pdf'})},{path:'project.json',blob:new Blob([JSON.stringify(data,null,2)],{type:'application/json'})},{path:'files.json',blob:new Blob([JSON.stringify({format:'vfx-tools.delivery.1',files:inventory},null,2)],{type:'application/json'})});
  const blob=await createStoredZIP(entries,progress=>{$('fileProgress').textContent=t('Preparing delivery…')+' '+progress+'%'}),filename=[pdfFilePart(data.project.name,'Proyecto'),localDate(),language==='es'?'Entrega-VFX':'VFX-Delivery'].join('_')+'.zip';
  const file=new File([blob],filename,{type:'application/zip',lastModified:created.getTime()});preparedPackage={file,url:URL.createObjectURL(file),projectId:data.project.id,warnings:result.warnings};closeDlg();if(route===origin)go('packageReady');else toast(t('Delivery ready'));
 }catch(e){$('dlgBody').innerHTML='<h2>'+t('Delivery not created')+'</h2><p>'+esc(e.message||t('Could not prepare the delivery. Please retry.'))+'</p><button class="secondary" onclick="closeDlg()">'+t('Close')+'</button>'}finally{packageBusy=false}
}

// ZIP method 0 (stored), UTF-8 names and CRC32; reads in 1 MiB slices, never
// materializes whole originals as base64 or a single ArrayBuffer. ZIP32 limits
// are checked before processing. Spec: https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT
const zipCRCTable=Uint32Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0});
async function createStoredZIP(entries,onProgress=()=>{}){
 const encoder=new TextEncoder(),planned=entries.map(e=>({...e,name:encoder.encode(e.path)}));
 const expected=22+planned.reduce((n,e)=>n+76+e.name.length*2+e.blob.size,0);
 if(planned.length>=65535||planned.some(e=>e.blob.size>=0xffffffff||e.name.length>65535)||expected>=0xffffffff)throw Error(t('This delivery exceeds the 4 GB ZIP limit. Save large files individually from their setup.'));
 const parts=[],central=[];let offset=0,done=0;const total=planned.reduce((n,e)=>n+e.blob.size,0);
 for(const e of planned){let crc=0xffffffff;for(let start=0;start<e.blob.size;start+=1048576){const chunk=new Uint8Array(await e.blob.slice(start,start+1048576).arrayBuffer());for(const byte of chunk)crc=zipCRCTable[(crc^byte)&255]^(crc>>>8);done+=chunk.length;onProgress(Math.floor(done/Math.max(1,total)*100));await new Promise(r=>setTimeout(r,0))}crc=(crc^0xffffffff)>>>0;
  const date=e.date instanceof Date&&!isNaN(e.date)?e.date:new Date(),year=Math.max(1980,Math.min(2107,date.getFullYear())),day=((year-1980)<<9)|((date.getMonth()+1)<<5)|date.getDate(),time=(date.getHours()<<11)|(date.getMinutes()<<5)|Math.floor(date.getSeconds()/2);
  const local=new Uint8Array(30+e.name.length),l=new DataView(local.buffer);l.setUint32(0,0x04034b50,true);l.setUint16(4,20,true);l.setUint16(6,0x800,true);l.setUint16(10,time,true);l.setUint16(12,day,true);l.setUint32(14,crc,true);l.setUint32(18,e.blob.size,true);l.setUint32(22,e.blob.size,true);l.setUint16(26,e.name.length,true);local.set(e.name,30);
  const center=new Uint8Array(46+e.name.length),c=new DataView(center.buffer);c.setUint32(0,0x02014b50,true);c.setUint16(4,20,true);c.setUint16(6,20,true);c.setUint16(8,0x800,true);c.setUint16(12,time,true);c.setUint16(14,day,true);c.setUint32(16,crc,true);c.setUint32(20,e.blob.size,true);c.setUint32(24,e.blob.size,true);c.setUint16(28,e.name.length,true);c.setUint32(42,offset,true);center.set(e.name,46);parts.push(local,e.blob);central.push(center);offset+=local.length+e.blob.size;
 }
 const length=central.reduce((n,e)=>n+e.length,0),end=new Uint8Array(22),v=new DataView(end.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,planned.length,true);v.setUint16(10,planned.length,true);v.setUint32(12,length,true);v.setUint32(16,offset,true);return new Blob([...parts,...central,end],{type:'application/zip'});
}
