// Presentation-only translations. Stored enum values, user text and IDs never change.
const ES={
'App settings':'Ajustes de la app',
'System follows the language of this device.':'Sistema utiliza el idioma de este dispositivo.',
'Screen information':'Información de pantalla',
'Copy screen diagnostics':'Copiar diagnóstico de pantalla',
'Screen diagnostics copied':'Diagnóstico de pantalla copiado',
'Update ready. Save your changes, then tap to reload.':'Actualización lista. Guarda tus cambios y toca aquí para recargar.',
"Set up equipment":"Configurar equipo",
"Register a camera and a lens before creating shots.":"Registra al menos una cámara y un lente antes de crear shots.",
"Ready":"Listo",
"Required":"Requerido",
"Not registered yet":"Aún no registrado",
"Continue to shoot":"Continuar a rodaje",
"Select shot equipment":"Seleccionar equipo del shot",
"Open shot":"Abrir shot",
"Delete shot":"Borrar shot",
"This deletes the shot, its notes, measurements and captures from this device.":"Se borrarán el shot, sus notas, medidas y capturas de este dispositivo.",
"captures":"capturas",
"Finish saving the capture before deleting this shot.":"Termina de guardar la captura antes de borrar este shot.",
"Shot deleted":"Shot borrado",
"Could not delete the shot. Please retry.":"No se pudo borrar el shot. Vuelve a intentar.",
"PDF ready":"PDF listo",
"Save PDF":"Guardar PDF",
"Share PDF":"Compartir PDF",
"Your PDF is ready to save or share with this filename.":"Tu PDF está listo para guardar o compartir con este nombre.",
"Could not share the PDF. Use Save PDF.":"No se pudo compartir. Usa Guardar PDF.",
"Page":"Página",
"Continued":"Continuación",
"Some images could not be included. See the labels in the PDF.":"Algunas imágenes no se pudieron incluir. Consulta las indicaciones del PDF.",
'/ LIBRARY':'/ BIBLIOTECA','/ EXPORT':'/ EXPORTAR',
'Type to confirm':'Escribe para confirmar','camera':'cámara','lens':'lente','12 cells across short side':'12 celdas en el lado corto','18 cells across short side':'18 celdas en el lado corto','24 cells across short side':'24 celdas en el lado corto','Letter · 216 × 279 mm':'Carta · 216 × 279 mm',
'Welcome':'Bienvenido','Projects saved on this device.':'Proyectos guardados en este dispositivo.','Projects':'Proyectos','No projects yet.':'Aún no hay proyectos.','+ New project':'+ Nuevo proyecto','New project':'Nuevo proyecto','Project name':'Nombre del proyecto','Display name':'Nombre','Operator':'Operador','Create project':'Crear proyecto','Enter a project name.':'Escribe el nombre del proyecto.','Project created':'Proyecto creado','Project settings':'Ajustes del proyecto','+ New shot':'+ Nuevo shot','No shots yet.':'Aún no hay shots.','Shot log':'Lista de shots','shoot days':'días de rodaje','TOTAL':'TOTAL','Back':'Volver','Equipment':'Equipo','Library':'Biblioteca','LIBRARY':'BIBLIOTECA','SHOOT':'RODAJE','TOOLS':'HERRAMIENTAS','EXPORT':'EXPORTAR','Tools':'Herramientas','Export':'Exportar',
'Camera':'Cámara','Lens':'Lente','Cameras':'Cámaras','Lenses':'Lentes','+ Add camera':'+ Agregar cámara','+ Add lens':'+ Agregar lente','Add camera':'Agregar cámara','Add lens':'Agregar lente','Edit camera':'Editar cámara','Edit lens':'Editar lente','Select camera':'Seleccionar cámara','Select lens':'Seleccionar lente','Save camera':'Guardar cámara','Save lens':'Guardar lente','Delete camera':'Eliminar cámara','Delete lens':'Eliminar lente','Lens type':'Tipo de lente','Camera ID':'ID de cámara','Lens ID':'ID de lente','Manufacturer':'Fabricante','Model':'Modelo','Sensor format':'Formato del sensor','Lens mount':'Montura del lente','Mount':'Montura','Focal / range':'Focal / rango','Preset values are starting points. Confirm the actual equipment on set.':'Los valores predefinidos son una base. Confirma el equipo real en el set.','Default FPS':'FPS predeterminados','Custom FPS':'FPS personalizados','Custom color / gamma':'Color / gamma personalizados','Custom / Other':'Personalizado / Otro','Custom':'Personalizado','All fields are editable.':'Todos los campos se pueden editar.','An ID and model are required.':'Se requieren un ID y un modelo.','That equipment ID already exists.':'Ese ID de equipo ya existe.','FPS must be a positive number.':'Los FPS deben ser un número positivo.','Camera saved':'Cámara guardada','Lens saved':'Lente guardado','Delete':'Eliminar','Cancel':'Cancelar','Delete and unassign':'Eliminar y desasignar','Deleted and unassigned':'Eliminado y desasignado','is used by':'se usa en','The equipment will be unassigned. Recorded camera-state values remain.':'El equipo se desasignará. Los valores registrados en los shots se conservarán.',
'PRODUCTION':'PRODUCCIÓN','Shot':'Shot','Scene':'Escena','Setup':'Setup','CURRENT TAKE':'TOMA ACTUAL','TAKE':'TOMA','Take':'Toma','SC':'ESC','SCENE':'ESCENA','SETUP':'SETUP','Shot slate':'Claqueta del shot','Previous take':'Toma anterior','Next take':'Siguiente toma','Camera state':'Ajustes de cámara','INHERITED → EDITABLE':'HEREDADO → EDITABLE','AUTOSAVE':'GUARDADO AUTOMÁTICO','EMPTY':'SIN DATO','INHERITED':'HEREDADO','PRESET':'PREDEFINIDO','USER ENTERED':'INGRESADO','Camera settings inherited from':'Ajustes de cámara heredados de','Clear inherited values':'Limpiar valores heredados','Use a unique, non-empty shot name.':'Escribe un nombre de shot único.','Focal':'Focal','Focus':'Enfoque','White balance':'Balance de blancos','Frame rate':'Frecuencia','Movement':'Movimiento','Sensor mode':'Modo de sensor','Color / gamma':'Color / gamma','Shutter':'Obturador','Shutter representation':'Unidad del obturador','Shutter value':'Valor del obturador','Angle °':'Ángulo °','Fraction 1/s':'Fracción 1/s','Denominator · exposure is 1 / value seconds':'Denominador · exposición de 1 / valor segundos','Angle / degrees':'Ángulo / grados','Set FPS to calculate the equivalent angle or fraction.':'Indica los FPS para calcular el ángulo o la fracción equivalente.','Set FPS before converting shutter units.':'Indica los FPS antes de convertir el obturador.','Choose a shutter value.':'Selecciona un valor de obturador.','Equivalent':'Equivalente','at':'a','Enter a positive denominator.':'Escribe un denominador positivo.','Use an angle greater than 0 and up to 360°.':'Usa un ángulo mayor que 0 y hasta 360°.','Use value':'Usar valor',
'Shot type':'Tipo de shot','Select type':'Selecciona un tipo','Remove type':'Quitar tipo','+ Add type':'+ Agregar tipo','This type is already selected.':'Este tipo ya está seleccionado.','Done':'Listo','Capture photo / video':'Capturar foto / video','+ Add measurement':'+ Agregar medida','Notes':'Notas','Note · autosaved':'Nota · guardado automático','Type or use keyboard dictation.':'Escribe o usa el dictado del teclado.','Shot records':'Registros del shot','References':'Referencias','Photos & videos':'Fotos y videos','Measurements':'Medidas','Values, method & confidence':'Valores, método y precisión','Previous captures':'Capturas anteriores','Plates & audio from earlier versions':'Plates y audio de versiones anteriores','Shoot date':'Fecha de rodaje','Change only when needed':'Cambiar solo si es necesario','Shoot date updated':'Fecha de rodaje actualizada','Saving capture…':'Guardando captura…','The shot is no longer available.':'El shot ya no está disponible.','Capture saved':'Captura guardada','Capture not saved':'Captura sin guardar','The device could not store this capture. Keep this screen open, free storage, then retry.':'No se pudo guardar la captura. Mantén esta pantalla abierta, libera espacio y vuelve a intentar.','Retry save':'Reintentar guardado','Save file to device':'Guardar archivo en el dispositivo','Media file is unavailable on this device.':'El archivo no está disponible en este dispositivo.','Captured reference':'Imagen de referencia','✓ ON DEVICE · TAKE':'✓ EN EL DISPOSITIVO · TOMA','Type':'Tipo','Note':'Nota','Edit catalog':'Editar detalles','No references yet.':'Aún no hay referencias.','Measurement':'Medida','From':'Desde','To':'Hasta','Value':'Valor','Unit':'Unidad','Source / method':'Fuente / método','Custom method':'Método personalizado','Confidence':'Precisión','Save measurement':'Guardar medida','Enter the custom method.':'Escribe el método personalizado.','Measurement saved':'Medida guardada','No measurements yet.':'Aún no hay medidas.',
'Screen assets':'Imágenes de pantalla','Green & blue · fullscreen, share, PNG':'Verde y azul · pantalla completa, compartir, PNG','Tracking markers':'Marcadores de tracking','Cross, circle & checker · physical sizes':'Cruz, círculo y tablero · tamaños físicos','Lens distortion':'Distorsión de lente','Calibration image · fullscreen, share, PNG':'Imagen de calibración · pantalla completa, compartir, PNG','Scale references':'Referencias de escala','Metric reference · print at actual size':'Referencia métrica · imprimir a tamaño real','Color':'Color','Green':'Verde','Blue':'Azul','Pattern':'Patrón','None':'Ninguno','4 corners':'4 esquinas','5 point':'5 puntos','Grid':'Cuadrícula','Aspect':'Proporción','Width / px':'Ancho / px','Height / px':'Alto / px','Screen asset preview':'Vista previa de pantalla','Fullscreen':'Pantalla completa','Share':'Compartir','Save PNG':'Guardar PNG','Use whole dimensions between 64 and 4096 px.':'Usa dimensiones enteras entre 64 y 4096 px.','Use whole dimensions from 64 to 4096 px.':'Usa dimensiones enteras entre 64 y 4096 px.','px · chroma-family tracking points':'px · puntos de tracking para croma','px · square cells · center crosshair':'px · celdas cuadradas · cruz central','Wait for a valid preview.':'Espera una vista previa válida.','Wait for a valid grid preview.':'Espera una vista previa válida de la cuadrícula.','Sharing unavailable. PNG saved instead.':'No se pudo compartir. Se guardó el PNG.','PNG saved instead.':'Se guardó el PNG.','Style':'Estilo','Cross':'Cruz','Circle':'Círculo','Checker':'Tablero','Physical size':'Tamaño físico','Paper':'Papel','Count':'Cantidad','Print at 100% / actual size. Disable fit-to-page. IDs are reserved when you prepare a sheet.':'Imprime al 100 % / tamaño real, sin ajustar a la página. Los IDs se reservan al preparar una hoja.','Print / Save PDF':'Imprimir / Guardar PDF','A square-cell calibration grid with a center crosshair. Save or share it as an image.':'Cuadrícula de calibración con celdas cuadradas y cruz central. Guárdala o compártela como imagen.','Grid density':'Densidad de cuadrícula','Cells across short edge':'Celdas en el lado corto','Distortion grid preview':'Vista previa de distorsión','100 mm reference with 10 mm divisions. Verify with a physical ruler after printing.':'Referencia de 100 mm con divisiones de 10 mm. Verifica con una regla física después de imprimir.','VFX Tools · Scale reference':'VFX Tools · Referencia de escala','Print at actual size / 100%.':'Imprimir a tamaño real / 100 %.','Exit fullscreen':'Salir de pantalla completa',
'Project report / PDF':'Reporte del proyecto / PDF','All':'Todos los','shots · camera states, notes & measurements':'shots · cámara, notas, medidas y fotos','Project JSON':'JSON del proyecto','Full structured project metadata':'Metadatos completos del proyecto','Shot CSV':'CSV de shots','Camera states & acquisition counts':'Ajustes de cámara y conteo de registros','Project backup':'Respaldo del proyecto','Metadata + original media in one file':'Metadatos y archivos originales en un solo archivo','Current shot / PDF':'Shot actual / PDF','only':'solamente','JSON and CSV contain metadata. Use project backup to include original photos and videos.':'JSON y CSV contienen metadatos. El respaldo del proyecto incluye las fotos y los videos originales.','Create a shot before exporting a report.':'Crea un shot antes de exportar un reporte.','Preparing PDF…':'Preparando PDF…','Image unavailable for this PDF. Original file remains in the project backup.':'No se pudo incluir esta imagen en el PDF. El original se conserva en el respaldo del proyecto.','Could not prepare the PDF. Please retry.':'No se pudo preparar el PDF. Vuelve a intentar.','None recorded.':'Sin registros.','Video · original included in project backup.':'Video · original incluido en el respaldo del proyecto.','Preparing backup with original media…':'Preparando respaldo con archivos originales…','Backup stopped: a media file is missing.':'Respaldo detenido: falta un archivo multimedia.','Backup ready':'Respaldo listo','Focus / m':'Enfoque / m','White balance / K':'Balance de blancos / K',
'PROJECT CODE ·':'CÓDIGO DEL PROYECTO ·','The project code stays stable when the display name changes.':'El identificador del proyecto se conserva al cambiar su nombre.','Save changes':'Guardar cambios','Delete project':'Eliminar proyecto','This removes this project and its captures from this device.':'Se eliminarán este proyecto y sus capturas del dispositivo.','Project deleted':'Proyecto eliminado','SAVING':'GUARDANDO','SAVED ON DEVICE':'GUARDADO EN EL DISPOSITIVO','NOT SAVED · RETRY':'SIN GUARDAR · REINTENTAR','Could not save. Free device storage, then tap Retry.':'No se pudo guardar. Libera espacio y toca Reintentar.','ON DEVICE':'EN EL DISPOSITIVO','SAVING CAPTURE':'GUARDANDO CAPTURA','CAPTURE NOT SAVED':'CAPTURA SIN GUARDAR','ACTION FAILED · RETRY':'ERROR · REINTENTAR','Storage unavailable.':'Almacenamiento no disponible.','Allow browser storage, then reload to open your projects.':'Permite el almacenamiento del navegador y recarga para abrir tus proyectos.','Retry':'Reintentar','Language':'Idioma','System':'Sistema','Main navigation':'Navegación principal','Confirm deletion':'Confirmar eliminación','Capture photo or video':'Capturar foto o video','VFX Tools, projects':'VFX Tools, proyectos',
'Cleanup':'Limpieza','Screen':'Pantalla','Greenscreen':'Pantalla verde','Set Extension':'Extensión de set','Cg Object':'Objeto CG','Cg Character':'Personaje CG','Digital Double':'Doble digital','Environment':'Entorno','Vehicle':'Vehículo','Beauty':'Retoque','Matte Painting':'Matte painting','Simulation':'Simulación','Other':'Otro','General':'General','Lighting':'Iluminación','Set':'Set','Material':'Material','Actor':'Actor','Prop':'Utilería','Tracking':'Tracking','Continuity':'Continuidad','Prime':'Fijo','Zoom':'Zoom','Anamorphic':'Anamórfico','Tripod':'Trípode','Handheld':'Cámara en mano','Dolly':'Dolly','Crane':'Grúa','Gimbal':'Gimbal','Drone':'Dron','Vehicle Rig':'Rig de vehículo','Motion Control':'Control de movimiento','Clear':'Sin filtro','Laser':'Láser','Tape':'Cinta','Manual':'Manual','Phone Sensor':'Sensor del teléfono','Calculated':'Calculado','Estimated':'Estimado','Exact':'Exacta','Measured':'Medida','Approximate':'Aproximada','Reference':'Referencia'
};
let languagePreference='system';try{languagePreference=localStorage.getItem('vfx-tools-language')||'system'}catch{}
function currentLanguage(){return languagePreference==='system'?((navigator.languages?.[0]||navigator.language||'en').toLowerCase().startsWith('es')?'es':'en'):languagePreference}
function t(value){return currentLanguage()==='es'?(ES[value]??value):value}
function translateText(value){const trimmed=value.trim();if(Object.hasOwn(ES,trimmed))return value.replace(trimmed,t(trimmed));return value}
// Called on static source fragments before user data is interpolated.
function ui(fragment){if(currentLanguage()!=='es')return fragment;return fragment.replace(/(^|>)([^<>]*)(?=<|$)/g,(_,edge,text)=>edge+translateText(text)).replace(/(aria-label|alt)="([^"]*)"/g,(_,attr,text)=>attr+'="'+translateText(text)+'"')}
function updateLanguageControl(){document.documentElement.lang=currentLanguage();const control=document.getElementById('languageSelect');if(control){control.value=languagePreference;control.setAttribute('aria-label',t('Language'));control.options[0].textContent=t('System')}for(const [id,label] of [['nav','Main navigation'],['dlg','Confirm deletion'],['captureInput','Capture photo or video']])document.getElementById(id)?.setAttribute('aria-label',t(label));document.querySelector('.brand')?.setAttribute('aria-label',t('VFX Tools, projects'))}
function setLanguage(value){if(!['system','es','en'].includes(value))return;const inputs=[...document.querySelectorAll('main input,main textarea,main select')].map(el=>({id:el.id,value:el.value,checked:el.checked})),details=[...document.querySelectorAll('main details')].map(el=>el.open),scroll=window.scrollY;languagePreference=value;try{localStorage.setItem('vfx-tools-language',value)}catch{}render();for(const saved of inputs){const el=document.getElementById(saved.id);if(el){el.value=saved.value;if(el.type==='checkbox')el.checked=saved.checked}}document.querySelectorAll('main details').forEach((el,i)=>el.open=details[i]||false);updateLanguageControl();setSaveStatus(saveError?'NOT SAVED · RETRY':'ON DEVICE',saveError);window.scrollTo(0,scroll)}
window.addEventListener('languagechange',()=>{if(languagePreference==='system')setLanguage('system')});

function tr(value){return currentLanguage()==='es'?translateText(value):value}

