// Bundled PDF generation works offline and produces an actual named file.
let reportBusy=false,preparedPDF=null;
function clearPreparedPDF(){if(preparedPDF)URL.revokeObjectURL(preparedPDF.url);preparedPDF=null}
function pdfReadyScreen(){if(!preparedPDF){go('export',{},true);return}const f=preparedPDF.file;const canShare=!!navigator.canShare?.({files:[f]});$('main').innerHTML=pageTop(t('PDF ready'),t('Export'))+'<p>'+t('Your PDF is ready to save or share with this filename.')+'</p><p class="pdf-filename">'+esc(f.name)+'</p><div class="button-stack pdf-actions"><a id="savePDF" class="primary" href="'+preparedPDF.url+'" download="'+esc(f.name)+'">'+t('Save PDF')+'</a>'+(canShare?'<button class="secondary" onclick="sharePDF()">'+t('Share PDF')+'</button>':'')+'</div>'+(preparedPDF.warnings?'<p class="helper">'+t('Some images could not be included. See the labels in the PDF.')+'</p>':'')}
async function sharePDF(){if(!preparedPDF)return;const file=preparedPDF.file;try{await navigator.share({files:[file],title:file.name})}catch(e){if(e.name!=='AbortError')toast(t('Could not share the PDF. Use Save PDF.'))}}
async function report(scope='project'){
 if(reportBusy)return;const project=structuredClone(p()),all=scope==='shot'?shots(project).filter(h=>h.id===state.activeShotId):shots(project);if(!all.length&&(scope==='shot'||!projectFiles(project).length))return toast(t('Create a shot before exporting a report.'));
 const filename=pdfTitle('report',project,scope==='shot'?all[0].code:'')+'.pdf',operator=project.operator??state.operator,origin=route,language=currentLanguage(),created=new Date();reportBusy=true;toast(t('Preparing PDF…'));
 try{const result=await buildReportPDF({project,all,operator,language,created,title:filename.slice(0,-4),setupIds:scope==='shot'?all.map(h=>h._u.id):null});const file=new File([result.bytes],filename,{type:'application/pdf',lastModified:created.getTime()});clearPreparedPDF();preparedPDF={file,url:URL.createObjectURL(file),projectId:project.id,warnings:result.warnings};if(route===origin)go('pdfReady');else toast(t('PDF ready'))}catch(e){toast(t('Could not prepare the PDF. Please retry.'));console.error(e)}finally{reportBusy=false}
}
async function buildReportPDF({project,all,operator,language,created,title,inventory=null,setupIds=null}){
 const {PDFDocument,StandardFonts,rgb}=PDFLib,doc=await PDFDocument.create(),regular=await doc.embedFont(StandardFonts.Helvetica),bold=await doc.embedFont(StandardFonts.HelveticaBold),tr=value=>language==='es'?(ES[value]??value):value;
 const prettyValue=value=>tr(String(value||'').replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase()));
 doc.setTitle(title);doc.setAuthor(operator||'VFX Tools');doc.setCreator('VFX Tools');doc.setCreationDate(created);doc.setLanguage(language);
 const W=595.28,H=841.89,M=36,CW=W-2*M,bottom=42,ink=rgb(.08,.08,.09),muted=rgb(.38,.38,.42),line=rgb(.82,.82,.85),measure=document.createElement('canvas').getContext('2d');let page,y,warnings=0,shotLabel='';
 let banner;try{const response=await fetch('./assets/vfx-tools-banner.png');if(!response.ok)throw Error('Banner unavailable');banner=await doc.embedPng(await response.arrayBuffer())}catch{banner=null}
 function canEncode(text,font){try{font.encodeText(text);return true}catch{return false}}
 function width(text,size,font){if(canEncode(text,font))return font.widthOfTextAtSize(text,size);measure.font=(font===bold?'bold ':'')+size+'px Arial';return measure.measureText(text).width}
 function wrap(value,max,size,font){const result=[];for(const paragraph of String(value??'—').replace(/\r\n?/g,'\n').replace(/\t/g,'    ').split('\n')){let current='';for(const word of paragraph.split(/(\s+)/)){if(width(current+word,size,font)<=max){current+=word;continue}if(current.trim()){result.push(current.trimEnd());current=''}if(width(word,size,font)<=max){current=word.trimStart();continue}for(const ch of word){if(current&&width(current+ch,size,font)>max){result.push(current);current=''}current+=ch}}result.push(current.trimEnd())}return result.length?result:['']}
 async function drawLine(text,x,top,size=10,font=regular,color=ink){if(!text)return;if(canEncode(text,font)){page.drawText(text,{x,y:top-size,size,font,color});return}const scale=3,canvas=document.createElement('canvas');canvas.width=Math.ceil(width(text,size,font)*scale)+6;canvas.height=Math.ceil(size*1.7*scale);const ctx=canvas.getContext('2d');ctx.scale(scale,scale);ctx.font=(font===bold?'bold ':'')+size+'px Arial';ctx.fillStyle='#151518';ctx.textBaseline='top';ctx.fillText(text,0,0);const image=await doc.embedPng(canvas.toDataURL('image/png'));page.drawImage(image,{x,y:top-canvas.height/scale,width:canvas.width/scale,height:canvas.height/scale})}
 async function newPage(){page=doc.addPage([W,H]);y=H-M;page.drawRectangle({x:M,y:y-42,width:CW,height:42,color:rgb(0,0,0)});if(banner){const dims=banner.scaleToFit(CW-24,34);page.drawImage(banner,{x:(W-dims.width)/2,y:y-38+(34-dims.height)/2,width:dims.width,height:dims.height})}else await drawLine('VFX Tools',M+12,y-9,20,bold,rgb(1,1,1));y-=54;if(shotLabel)await paragraph(shotLabel+' · '+tr('Continued'),11,bold)}
 async function ensure(height){if(y-height<bottom)await newPage()}
 async function paragraph(value,size=10,font=regular,max=CW,x=M){for(const text of wrap(value,max,size,font)){await ensure(size*1.45);await drawLine(text,x,y,size,font);y-=size*1.45}y-=3}
 async function heading(text){await ensure(45);y-=8;await paragraph(text,12,bold)}
 async function tableRow(values,widths){const cells=values.map((value,i)=>wrap(value??'—',widths[i]-10,9,i%2===0?bold:regular));let max=Math.max(...cells.map(x=>x.length));for(let from=0;from<max;){await ensure(22);const count=Math.min(max-from,Math.max(1,Math.floor((y-bottom-8)/13))),height=count*13+8;let x=M;for(let i=0;i<cells.length;i++){for(let n=0;n<count;n++)if(cells[i][from+n]!==undefined)await drawLine(cells[i][from+n],x+4,y-4-n*13,9,i%2===0?bold:regular);x+=widths[i]}y-=height;page.drawLine({start:{x:M,y},end:{x:W-M,y},thickness:.5,color:line});from+=count}}
 const equipment=(list,id)=>{const item=list.find(x=>x.id===id);return item?[item.code,item.make,item.model].filter(Boolean).join(' · '):'—'};
 for(let index=0;index<all.length;index++){
  const h=all[index],c=h.camera||{};shotLabel='';await newPage();await paragraph(project.name,20,bold);await paragraph(tr('Operator')+': '+(operator||'—')+' · '+created.toLocaleString(language),9);await paragraph((index+1)+' / '+all.length+' shots',9);y-=5;await paragraph(h.code,18,bold);shotLabel=h.code;
  await paragraph(h._d.date+' · '+tr('SC')+' '+(h._s.code||'—')+' · SETUP '+(h._u.code||'—')+' · '+tr('TAKE')+' '+h.take,9);if(h.types?.length)await paragraph(h.types.filter(Boolean).map(prettyValue).join(' · '),9);
  const shutter=c.shutterMode==='fraction'?(c.shutterFraction?'1/'+compactNumber(c.shutterFraction)+' s':'—'):(c.shutter!=null?compactNumber(c.shutter)+'°':'—');
  const fields=[['Camera',equipment(project.cameras,c.cameraId)],['Lens',equipment(project.lenses,c.lensId)],['Focal / mm',c.focal],['Focus / m',c.focus],['T / F stop',c.aperture],['EI / ISO',c.ei],['White balance / K',c.wb],['FPS',c.fps],['ND',c.nd],['Shutter',shutter],['Movement',c.movement?prettyValue(c.movement):null],['Sensor mode',c.sensorMode],['Color / gamma',c.color]];
  for(let i=0;i<fields.length;i+=2){const a=fields[i],b=fields[i+1]||['',''];await tableRow([tr(a[0]),a[1],tr(b[0]),b[1]],[CW*.23,CW*.27,CW*.23,CW*.27])}
  await heading(tr('Measurements'));if(!h.measurements?.length)await paragraph(tr('None recorded.'));for(const m of h.measurements||[])await paragraph(tr('Take')+' '+m.take+' · '+m.from+' → '+m.to+' · '+m.value+' '+m.unit+' · '+prettyValue(m.method)+' / '+prettyValue(m.confidence));
  await heading(tr('Notes'));if(!h.notes?.length)await paragraph(tr('None recorded.'));for(const n of h.notes||[])await paragraph(tr('Take')+' '+(n.take||1)+' · '+n.text);
  await heading(tr('References'));const refs=[...(h.media||[]),...(h.plates||[])];if(!refs.length)await paragraph(tr('None recorded.'));
  for(const m of refs){const caption=tr('Take')+' '+(m.take||1)+' · '+prettyValue(m.tag||m.type||'GENERAL')+(m.note?' · '+m.note:'');const entry=await get('media',m.mediaId);if(!entry){warnings++;await paragraph(caption);await paragraph(tr('Media file is unavailable on this device.'));continue}if(entry.kind==='video'||entry.type?.startsWith('video/')){await paragraph(caption);await paragraph(tr('Video · original included in project backup.'));continue}
   try{const image=await embedReference(doc,mediaBlob(entry));const dims=image.scaleToFit(CW,190);await ensure(dims.height+34);page.drawRectangle({x:M,y:y-dims.height,width:dims.width,height:dims.height,color:rgb(.2,.2,.2)});page.drawImage(image,{x:M,y:y-dims.height,width:dims.width,height:dims.height});y-=dims.height+6;await paragraph(caption,9);y-=6}catch{warnings++;await paragraph(caption);await paragraph(tr('Image unavailable for this PDF. Original file remains in the project backup.'))}
  }
 }
 for(const info of projectSetups(project)){const u=info.setup;if(!u.attachments?.length||(setupIds&&!setupIds.includes(u.id)))continue;shotLabel='';await newPage();await paragraph(project.name,20,bold);await heading(tr('Setup files & LiDAR'));const context=info.day.date+' · '+tr('Scene')+' '+(info.scene.code||'—')+' · Setup '+(u.code||'—');await paragraph(context,12,bold);shotLabel=context;await paragraph(tr('Shared by shots')+': '+(u.shots.map(h=>h.code).join(', ')||'—'));await paragraph(tr('Original files are delivered separately in the delivery ZIP.'));
  for(const a of u.attachments){await heading(a.name);await paragraph(fileSize(a.size),9);const item=inventory?.find(x=>x.setupId===u.id&&x.mediaId===a.mediaId);if(item)await paragraph(item.path,9);else if(!await get('media',a.mediaId)){warnings++;await paragraph(tr('Media file is unavailable on this device.'))}}
 }
 const pages=doc.getPages();for(let i=0;i<pages.length;i++){page=pages[i];await drawLine('VFX Tools',M,25,8,regular,muted);const label=tr('Page')+' '+(i+1)+' / '+pages.length;await drawLine(label,W-M-width(label,8,regular),25,8,regular,muted)}
 return {bytes:await doc.save(),warnings};
}
async function embedReference(doc,blob){const url=URL.createObjectURL(blob);try{const img=new Image();img.src=url;await img.decode();const scale=Math.min(1,1600/Math.max(img.naturalWidth,img.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#333';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);return await doc.embedJpg(canvas.toDataURL('image/jpeg',.9))}finally{URL.revokeObjectURL(url)}}
