const {chromium,webkit}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto');
(async()=>{
 const engine=process.env.TEST_ENGINE==='webkit'?webkit:chromium,tag=engine===webkit?'webkit':'chromium';
 const browser=await engine.launch({headless:true,...(engine===chromium?{channel:process.env.BROWSER_CHANNEL||'msedge'}:{})});
 const context=await browser.newContext({viewport:{width:393,height:852},locale:'es-MX',isMobile:true,hasTouch:true}),page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));fs.mkdirSync('test-output',{recursive:true});
 await page.goto(process.env.APP_URL||'http://127.0.0.1:4173');await page.waitForFunction(()=>typeof db!=='undefined'&&db);
 await page.evaluate(async()=>{const pr={id:'test-project',name:'LiDAR Día 1',code:'LIDAR',cameras:[],lenses:[],days:[]};state.projects=[pr];state.activeProjectId=pr.id;for(let n=1;n<=3;n++){const u=ensureSetup(pr,'2026-09-23',n===3?'02':'01','A');u.shots.push({id:'shot-'+n,code:'SH00'+n,take:1,camera:{},types:[],media:[],plates:[],voice:[],notes:[],measurements:[]})}state.activeShotId='shot-1';await save();go('shot')});
 await page.getByRole('button',{name:/Archivos y LiDAR/}).click();await page.getByRole('heading',{name:'Archivos y LiDAR'}).waitFor();
 const setup=await page.evaluate(()=>activeSetup().setup.id);assert.match(await page.locator('.setup-context').innerText(),/2026-09-23.*01.*A/);
 const data=Buffer.alloc(2097171);for(let i=0;i<data.length;i++)data[i]=i%251;
 const files=[{name:'escáner.e57',mimeType:'',buffer:data},{name:'modelo.obj',mimeType:'text/plain',buffer:Buffer.from('mtllib modelo.mtl\nv 0 0 0\n')},{name:'modelo.mtl',mimeType:'text/plain',buffer:Buffer.from('newmtl scan\n')},{name:'escáner.e57',mimeType:'application/octet-stream',buffer:Buffer.from('duplicate')},{name:'empty.custom',mimeType:'',buffer:Buffer.alloc(0)}];
 const chooserPromise=page.waitForEvent('filechooser');await page.getByRole('button',{name:'+ Agregar archivos',exact:true}).click();const chooser=await chooserPromise;assert.equal(chooser.isMultiple(),true);await chooser.setFiles(files);await page.waitForFunction(()=>!attachmentBusy&&activeSetup().setup.attachments?.length===5);
 assert.equal(await page.evaluate(()=>raw().attachments),undefined);assert.equal(await page.locator('.attachment-card').count(),5);
 await page.evaluate(async()=>{await selectShot('shot-2');go('attachments',{setupId:shot()._u.id})});assert.equal(await page.locator('.attachment-card').count(),5);
 await page.evaluate(async()=>{await selectShot('shot-3');go('attachments',{setupId:shot()._u.id})});assert.equal(await page.locator('.attachment-card').count(),0);
 // Same setup code in another scene is independent.
 await page.evaluate(async()=>{await addAttachments([new File(['other scene'],'scan.ply')],{projectId:p().id,setupId:shot()._u.id})});
 await page.evaluate(async()=>{await selectShot('shot-1');const id=uid(),canvas=document.createElement('canvas');canvas.width=80;canvas.height=40;canvas.getContext('2d').fillRect(0,0,80,40);const blob=await new Promise(r=>canvas.toBlob(r));await put('media',{id,bytes:await blob.arrayBuffer(),name:'reference.png',type:'image/png',shotId:raw().id});raw().media.push({id:uid(),mediaId:id,take:1});await save();go('attachments',{setupId:shot()._u.id})});
 // Save original bytes with a fresh user gesture.
 await page.locator('.attachment-card').first().getByRole('button',{name:'Guardar archivo'}).click();const oneDownload=page.waitForEvent('download');await page.locator('#dlg a').click();const one=await oneDownload;await one.saveAs('test-output/lidar-original-'+tag+'.e57');assert.deepEqual(fs.readFileSync('test-output/lidar-original-'+tag+'.e57'),data);await page.getByRole('button',{name:'Cerrar',exact:true}).click();
 // Reload old data and exercise offline code/resources.
 await page.evaluate(()=>navigator.serviceWorker.ready);if(engine===chromium){await page.reload();await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await context.setOffline(true)}
 await page.reload();await page.waitForSelector('#sh');await page.evaluate(()=>go('attachments',{setupId:shot()._u.id}));assert.equal(await page.locator('.attachment-card').count(),5);
 for(const [width,height] of [[320,740],[393,852],[852,393],[768,1024],[1180,820]]){await page.setViewportSize({width,height});for(const view of ['attachments','setups','export']){await page.evaluate(view=>go(view,{setupId:shot()._u.id}),view);await page.waitForTimeout(50);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.ok(await page.evaluate(()=>Math.abs(document.getElementById('nav').getBoundingClientRect().bottom-innerHeight)<1))}}
 await page.setViewportSize({width:393,height:852});await page.evaluate(()=>go('attachments',{setupId:shot()._u.id}));await page.screenshot({path:'test-output/setup-files-'+tag+'.png',fullPage:true});
 // Abort the complete batch: no metadata or original survives.
 await page.evaluate(()=>{window.originalTx=db.transaction.bind(db);db.transaction=(names,mode)=>{const tx=originalTx(names,mode);if(Array.isArray(names)&&mode==='readwrite')queueMicrotask(()=>tx.abort());return tx}});
 await page.evaluate(()=>addAttachments([new File(['bad'],'not-saved.las')],{projectId:p().id,setupId:shot()._u.id}));assert.equal(await page.evaluate(()=>shot()._u.attachments.length),5);assert.equal(await page.evaluate(async()=>{const req=store('media').getAll();return await new Promise(r=>{req.onsuccess=()=>r(req.result.some(x=>x.name==='not-saved.las'))})}),false);await page.evaluate(()=>{db.transaction=originalTx;closeDlg()});
 // Blob fallback handles WebKit clone errors, without duplicating records.
 await page.evaluate(()=>{window.originalCommit=commitFileState;window.triedFallback=false;commitFileState=(...args)=>{if(!triedFallback){triedFallback=true;return Promise.reject(new DOMException('Test','DataCloneError'))}return originalCommit(...args)}});
 await page.evaluate(()=>addAttachments([new File(['fallback'],'fallback.xyz')],{projectId:p().id,setupId:shot()._u.id}));assert.equal(await page.evaluate(()=>shot()._u.attachments.length),6);await page.evaluate(()=>{commitFileState=originalCommit});
 // Failure to delete retains the record and bytes, cancel is harmless.
 await page.evaluate(()=>confirmAttachmentDelete(activeSetup().setup.attachments.at(-1).id));await page.getByRole('button',{name:'Cancelar',exact:true}).click();assert.equal(await page.evaluate(()=>shot()._u.attachments.length),6);
 await page.evaluate(()=>{commitFileState=()=>Promise.reject(Error('Test'));confirmAttachmentDelete(activeSetup().setup.attachments.at(-1).id)});await page.locator('#deleteAttachment').click();await page.waitForFunction(()=>!attachmentBusy);assert.equal(await page.evaluate(()=>shot()._u.attachments.length),6);await page.evaluate(()=>{commitFileState=originalCommit;closeDlg()});
 await page.evaluate(()=>confirmAttachmentDelete(activeSetup().setup.attachments.at(-1).id));await page.locator('#deleteAttachment').click();await page.waitForFunction(()=>!attachmentBusy);assert.equal(await page.evaluate(()=>shot()._u.attachments.length),5);
 // Preserve metadata + originals in the legacy backup too.
 const backupDownload=page.waitForEvent('download');await page.evaluate(()=>exportBackup());const backup=await backupDownload;const backupPath='test-output/setup-backup-'+tag+'.json';await backup.saveAs(backupPath);const saved=JSON.parse(fs.readFileSync(backupPath));assert.equal(saved.media.length,7);assert.equal(saved.project.days[0].scenes[0].setups[0].attachments.length,5);
 await page.evaluate(()=>go('export'));await page.getByRole('button',{name:/Reporte y archivos \/ ZIP/}).click();await page.waitForSelector('#savePackage');const zipName=await page.locator('#savePackage').getAttribute('download');assert.match(zipName,/LiDAR_Día_1_\d{4}-\d{2}-\d{2}_Entrega-VFX.zip/);const zipDownload=page.waitForEvent('download');await page.locator('#savePackage').click();const zip=await zipDownload;await zip.saveAs('test-output/delivery-'+tag+'.zip');
 await page.evaluate(()=>{Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>true});Object.defineProperty(navigator,'share',{configurable:true,value:async({files})=>{window.sharedName=files[0].name}});packageReadyScreen()});await page.getByRole('button',{name:'Compartir ZIP',exact:true}).click();assert.equal(await page.evaluate(()=>sharedName),zipName);
 // A missing original prevents silently incomplete delivery.
 await page.evaluate(async()=>{window.missingId=shot()._u.attachments[0].mediaId;window.missingRecord=await get('media',missingId);await new Promise(r=>{const tx=db.transaction('media','readwrite');tx.objectStore('media').delete(missingId);tx.oncomplete=r});await exportPackage()});assert.equal(await page.evaluate(()=>preparedPackage),null);assert.match(await page.locator('#dlgBody').innerText(),/falta un archivo/);await page.evaluate(async()=>{await put('media',missingRecord);closeDlg()});
 // Rename/move a shot: setup assets remain at the original setup.
 await page.evaluate(()=>go('shot'));await page.locator('#su').fill('B');await page.locator('#su').blur();assert.equal(await page.evaluate(()=>shot()._u.attachments?.length||0),0);assert.equal(await page.evaluate(id=>projectSetups().find(x=>x.setup.id===id).setup.attachments.length,setup),5);
 // Deleting all shots in a setup retains its files and access from the project.
 await page.evaluate(()=>selectShot('shot-2'));await page.evaluate(()=>confirmShotDelete());await page.locator('#deleteShotBtn').click();await page.waitForFunction(()=>!shotDeleting);assert.equal(await page.evaluate(id=>projectSetups().find(x=>x.setup.id===id).setup.shots.length,setup),0);await page.evaluate(()=>go('setups'));assert.match(await page.locator('#main').innerText(),/5 archivos/);
 await page.evaluate(()=>exportPackage());await page.waitForSelector('#savePackage');const orphanDownload=page.waitForEvent('download');await page.locator('#savePackage').click();await (await orphanDownload).saveAs('test-output/orphan-delivery-'+tag+'.zip');
 // Reject oversized ZIPs before reading payloads; paths cannot traverse folders.
 assert.match(await page.evaluate(async()=>{try{await createStoredZIP([{path:'large.las',blob:{size:0xffffffff}}])}catch(e){return e.message}}),/4 GB/);
 assert.equal((await page.evaluate(()=>archivePart('../../evil.e57'))).includes('/'),false);
 // A rejected storage estimate leaves the entire batch untouched.
 await page.evaluate(async()=>{const descriptor=Object.getOwnPropertyDescriptor(navigator,'storage');Object.defineProperty(navigator,'storage',{configurable:true,value:{estimate:async()=>({usage:9,quota:10})}});await addAttachments([new File(['too big'],'quota.e57')],{projectId:p().id,setupId:projectSetups().find(x=>x.setup.attachments?.length===5).setup.id});if(descriptor)Object.defineProperty(navigator,'storage',descriptor);else delete navigator.storage});assert.match(await page.locator('#dlgBody').innerText(),/espacio/);assert.equal(await page.evaluate(()=>projectFiles(p()).length),7);await page.evaluate(()=>closeDlg());
 // Setups can still deliver all originals after their last shots are deleted.
 for(const id of ['shot-1','shot-3']){await page.evaluate(id=>selectShot(id),id);await page.evaluate(()=>confirmShotDelete());await page.locator('#deleteShotBtn').click();await page.waitForFunction(()=>!shotDeleting)}assert.equal(await page.evaluate(()=>shots().length),0);assert.equal(await page.evaluate(()=>projectFiles(p()).length),6);await page.evaluate(()=>exportPackage());await page.waitForSelector('#savePackage');assert.ok(await page.evaluate(()=>preparedPackage.file.size>2000000));
 // Project deletion cleans setup blobs even when the setup has no shots.
 await page.evaluate(()=>{go('projectSettings');confirmProjectDelete()});await page.locator('#deleteCode').fill('LIDAR');await page.locator('#deleteProjectBtn').click();await page.waitForFunction(()=>state.projects.length===0);assert.equal(await page.evaluate(async()=>new Promise(r=>{const req=store('media').count();req.onsuccess=()=>r(req.result)})),0);
 assert.deepEqual(errors,[]);await context.setOffline(false);await browser.close();console.log('PASS '+tag+': setup sharing/isolation, arbitrary multi-file bytes, backup, ZIP/PDF/offline/share, rollback/fallback, responsive layouts, moves/deletion retain setup files, project cleanup');
})().catch(e=>{console.error(e);process.exit(1)});
