const {chromium,webkit}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('fs');fs.mkdirSync('test-output',{recursive:true});
(async()=>{
 const engine=process.env.TEST_ENGINE==='webkit'?webkit:chromium,browser=await engine.launch({headless:true,...(engine===chromium?{channel:process.env.BROWSER_CHANNEL||'msedge'}:{})});
 const context=await browser.newContext({viewport:{width:393,height:852},hasTouch:true,isMobile:true,locale:'es-MX'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const click=name=>page.getByRole('button',{name,exact:true}).click(),fill=(id,value)=>page.locator('#'+id).fill(value),change=async(id,value)=>{await fill(id,value);await page.locator('#'+id).blur()};
 await page.goto(process.env.APP_URL||'http://127.0.0.1:4173');await page.getByRole('heading',{name:'Bienvenido',exact:true}).waitFor();assert.equal(await page.title(),'VFX Tools');assert.equal(await page.locator('html').getAttribute('lang'),'es');
 await click('+ Nuevo proyecto');assert.equal(await page.locator('#pc').count(),0);await fill('pn','Camera');await fill('op','Notes');await page.locator('#languageSelect').selectOption('en');assert.equal(await page.locator('#pn').inputValue(),'Camera');await page.locator('#languageSelect').selectOption('es');await click('Crear proyecto');
 await click('+ Nuevo shot');await page.waitForSelector('#sh');assert.equal(await page.locator('#sh').inputValue(),'SH001');assert.equal(await page.locator('#sc').inputValue(),'');assert.equal(await page.getByRole('button',{name:'Create shot',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Capturar foto / video',exact:true}).count(),1);
 await change('sh','SH101A');await change('sc','101');await change('su','A');await click('+ Agregar tipo');await page.locator('#shotType_0').selectOption('CG_CHARACTER');await click('+ Agregar tipo');await page.locator('#shotType_1').selectOption('SET_EXTENSION');assert.deepEqual(await page.evaluate(()=>raw().types),['CG_CHARACTER','SET_EXTENSION']);await click('Quitar tipo 1');assert.deepEqual(await page.evaluate(()=>raw().types),['SET_EXTENSION']);
 await page.locator('#cs_fps').selectOption('24');await page.locator('#shutterValue').selectOption('180');await click('Fracción 1/s');assert.equal(await page.locator('#shutterValue').inputValue(),'48');await page.locator('#cs_fps').selectOption('30');assert.equal(await page.evaluate(()=>raw().camera.shutter),225);await fill('cs_focal','35');await fill('shotNote','Camera <b>literal</b> & Notes');
 await click('+ Agregar medida');await fill('mf','Camera');await fill('mt','Actor');await fill('mv','8');await page.locator('#mu').selectOption('ft');await click('Guardar medida');await page.waitForSelector('#sh');assert.equal(await page.evaluate(()=>raw().measurements[0].si.value),2.4384);
 const first=await page.evaluate(()=>raw().id);
 await page.evaluate(()=>{captureContext={projectId:p().id,shotId:raw().id,take:raw().take,created:now()}});
 await page.locator('#captureInput').setInputFiles({name:'reference.png',mimeType:'image/png',buffer:fs.readFileSync('assets/vfx-tools-icon.png')});await page.waitForSelector('#captureTag');await page.locator('#captureTag').selectOption('TRACKING');await fill('captureNote','Reference ONE');await click('Listo');await page.waitForSelector('#sh');
 await click('+ Nuevo shot');await page.waitForFunction(id=>raw().id!==id,first);assert.equal(await page.locator('#cs_focal').inputValue(),'35');assert.equal(await page.locator('#sc').inputValue(),'101');await change('sh','SH101B');await fill('cs_focal','50');await click('Limpiar valores heredados');await page.waitForFunction(()=>document.getElementById('cs_fps').value==='');assert.equal(await page.locator('#cs_focal').inputValue(),'50');assert.equal(await page.locator('#cs_fps').inputValue(),'');await fill('shotNote','SECOND SHOT');
 await page.locator('.date-detail summary').click();await change('editShotDate','2026-09-20');await page.waitForFunction(()=>shot()._d.date==='2026-09-20');assert.equal(await page.evaluate(()=>shots().length),2);
 await page.evaluate(async()=>{const c=document.createElement('canvas');c.width=80;c.height=40;const ctx=c.getContext('2d');ctx.fillStyle='red';ctx.fillRect(0,0,80,40);const b=await new Promise(r=>c.toBlob(r));const id=uid();await put('media',{id,bytes:await b.arrayBuffer(),type:'image/png',kind:'image'});raw().media.push({id:uid(),mediaId:id,kind:'image',take:1,tag:'GENERAL',note:'Reference TWO'});await save()});
 await page.reload();await page.waitForSelector('#sh');assert.equal(await page.locator('#sh').inputValue(),'SH101B');assert.equal(await page.locator('#languageSelect').inputValue(),'es');
 const active=await page.evaluate(()=>state.activeShotId);await page.evaluate(async()=>{window.print=()=>window.printed=true;await report()});assert.equal(await page.evaluate(()=>window.printed),true);assert.equal(await page.locator('#printRoot .report-shot').count(),2);assert.equal(await page.locator('#printRoot .report-references img').count(),2);assert.equal(await page.evaluate(()=>[...$('printRoot').querySelectorAll('img')].every(i=>i.complete&&i.naturalWidth>0)),true);assert.equal(await page.evaluate(()=>state.activeShotId),active);const reportText=await page.locator('#printRoot').textContent();for(const text of ['SH101A','SH101B','Camera <b>literal</b> & Notes','SECOND SHOT','Reference ONE','Reference TWO','Operador: Notes'])assert.ok(reportText.includes(text),text);assert.equal(await page.locator('#printRoot b:has-text("literal")').count(),0);
 if(engine===chromium)await page.pdf({path:'test-output/report-022.pdf',preferCSSPageSize:true,printBackground:true});await page.evaluate(()=>report('shot'));assert.equal(await page.locator('#printRoot .report-shot').count(),1);
 await page.evaluate(()=>go('library'));await click('+ Agregar cámara');await page.locator('#libPreset').selectOption({label:'FX30'});await fill('lib_code','CAM A');await click('Guardar cámara');await page.waitForSelector('.library-columns');await page.evaluate(()=>editLibrary('lens'));await page.locator('#libPreset').selectOption({label:'FE 24–70mm F2.8 GM II'});await fill('lib_code','LENS A');await click('Guardar lente');await page.waitForSelector('.library-columns');
 const screens={};for(const name of ['projects','shoot','shot','library','tools','screen','markers','distortion','scale','export','projectSettings','measure','references','measurements']){await page.evaluate(name=>go(name),name);await page.waitForTimeout(100);screens[name]=await page.locator('main').innerText()};fs.writeFileSync('test-output/screens-es-022.json',JSON.stringify(screens,null,2));
 for(const [width,height] of [[320,740],[393,852],[768,1024],[820,1180],[1024,768],[1180,820],[1366,1024]]){await page.setViewportSize({width,height});for(const name of ['shoot','shot','library','tools','distortion']){await page.evaluate(name=>go(name),name);const d=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,nav:$('nav').getBoundingClientRect().toJSON()}));assert.ok(d.scroll<=d.width,name+' overflow '+width);assert.ok(Math.abs(d.nav.width-width)<1);assert.ok(d.nav.height>=90)}}
 await page.setViewportSize({width:393,height:852});await page.evaluate(()=>{go('shot');$('toast').classList.remove('show')});await page.screenshot({path:'test-output/phone-022.png'});await page.setViewportSize({width:1180,height:820});await page.screenshot({path:'test-output/ipad-022.png'});
 await page.locator('#languageSelect').selectOption('en');assert.equal(await page.getByRole('button',{name:'Capture photo / video',exact:true}).count(),1);assert.equal(await page.locator('#shotNote').inputValue(),'SECOND SHOT');await page.reload();await page.waitForSelector('#sh');assert.equal(await page.locator('html').getAttribute('lang'),'en');await page.locator('#languageSelect').selectOption('system');assert.equal(await page.locator('html').getAttribute('lang'),'es');
 await page.evaluate(()=>go('projects'));assert.equal(await page.getByRole('button',{name:/^Camera/}).count(),1);assert.deepEqual(errors,[]);
 if(engine===chromium){await page.evaluate(()=>navigator.serviceWorker.ready);await context.setOffline(true);await page.reload();await page.waitForSelector('#sh');assert.equal(await page.locator('.brand img').evaluate(i=>i.naturalWidth>0),true);await context.setOffline(false)}
 const en=await browser.newContext({locale:'en-US'}),enPage=await en.newPage();await enPage.goto(process.env.APP_URL||'http://127.0.0.1:4173');await enPage.getByRole('heading',{name:'Welcome',exact:true}).waitFor();assert.equal(await enPage.locator('#languageSelect').inputValue(),'system');
 console.log('PASS 0.2.2 '+(engine===webkit?'WebKit':'Chromium')+': locale switching, direct shots, tags, retained user data, shutter, camera inheritance, capture, 2-shot PDF with Blob/bytes images, equipment, responsive layouts and persistence');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});

