const {chromium,webkit}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict'),fs=require('fs');fs.mkdirSync('test-output',{recursive:true});
(async()=>{const engine=process.env.TEST_ENGINE==='webkit'?webkit:chromium,b=await engine.launch({headless:true,...(engine===chromium?{channel:process.env.BROWSER_CHANNEL||'msedge'}:{})});const context=await b.newContext({viewport:{width:393,height:852},locale:'es-MX',timezoneId:'America/Mexico_City',isMobile:true,hasTouch:true}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')console.log(m.text())});const click=name=>page.getByRole('button',{name,exact:true}).click();await page.goto(process.env.APP_URL||'http://127.0.0.1:4173');await click('+ Nuevo proyecto');await page.locator('#pn').fill('IPSY Día 1');await click('Crear proyecto');await page.getByRole('heading',{name:'Configurar equipo',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Continuar a rodaje',exact:true}).isDisabled(),true);await page.evaluate(()=>createShot());assert.equal(await page.evaluate(()=>shots().length),0);
await click('+ Agregar cámara');await page.locator('#libPreset').selectOption({label:'FX30'});await page.locator('#lib_code').fill('CAM A');await click('Guardar cámara');await page.getByRole('heading',{name:'Configurar equipo',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Continuar a rodaje',exact:true}).isDisabled(),true);await page.evaluate(()=>createShot());assert.equal(await page.evaluate(()=>shots().length),0);await click('+ Agregar lente');await page.locator('#libPreset').selectOption({label:'FE 24–70mm F2.8 GM II'});await page.locator('#lib_code').fill('LENS A');await click('Guardar lente');await page.getByRole('heading',{name:'Configurar equipo',exact:true}).waitFor();await click('Continuar a rodaje');await click('+ Nuevo shot');await page.waitForSelector('#sh');assert.ok(await page.locator('#cs_cameraId').inputValue());assert.ok(await page.locator('#cs_lensId').inputValue());const first=await page.evaluate(()=>raw().id);await page.locator('#shotNote').fill('Primera referencia: acción, niño, cámara. <literal>');
await page.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=700;canvas.height=360;const ctx=canvas.getContext('2d');ctx.fillStyle='#202434';ctx.fillRect(0,0,700,360);ctx.fillStyle='#b7a2fc';ctx.fillRect(40,40,260,240);ctx.fillStyle='white';ctx.font='30px sans-serif';ctx.fillText('REFERENCIA 01',330,190);const blob=await new Promise(r=>canvas.toBlob(r));const id=uid();await put('media',{id,bytes:await blob.arrayBuffer(),type:'image/png',kind:'image',shotId:raw().id});raw().media.push({id:uid(),mediaId:id,kind:'image',take:1,tag:'GENERAL',note:'Foto de prueba'});await save()});
await click('+ Nuevo shot');await page.waitForFunction(id=>raw().id!==id&&route.shotId===raw().id,first);const second=await page.evaluate(()=>raw().id);await page.locator('#shotNote').fill('SEGUNDO SHOT · referencias de cámara');await page.evaluate(async()=>{window.print=()=>{throw Error('Reports must not use native printing')};await report()});await page.getByRole('heading',{name:'PDF listo',exact:true}).waitFor();const filename=await page.locator('#savePDF').getAttribute('download');assert.match(filename,/^IPSY_Día_1_\d{4}-\d{2}-\d{2}_Reporte-VFX\.pdf$/);const downloadPromise=page.waitForEvent('download');await page.locator('#savePDF').click();const download=await downloadPromise;assert.equal(download.suggestedFilename(),filename);await download.saveAs('test-output/direct-report-025-'+(engine===webkit?'webkit':'chromium')+'.pdf');
await page.evaluate(()=>{Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>true});Object.defineProperty(navigator,'share',{configurable:true,value:async data=>{window.shared={name:data.files[0].name,type:data.files[0].type,size:data.files[0].size}}});pdfReadyScreen()});await click('Compartir PDF');assert.equal(await page.evaluate(()=>shared.name),filename);assert.equal(await page.evaluate(()=>shared.type),'application/pdf');assert.ok(await page.evaluate(()=>shared.size>1000));
await page.evaluate(()=>report('shot'));assert.match(await page.locator('#savePDF').getAttribute('download'),/_SH002_Reporte-VFX.pdf$/);
for(const [width,height] of [[320,740],[393,852],[736,414],[768,1024],[820,1180],[1180,820]]){await page.setViewportSize({width,height});for(const target of ['shoot','library','tools','export','shot']){await page.evaluate(target=>go(target),target);await page.waitForTimeout(40);const d=await page.evaluate(()=>({vh:visualViewport.height,nav:document.getElementById('nav').getBoundingClientRect().toJSON(),main:document.getElementById('main').getBoundingClientRect().toJSON(),dock:document.getElementById('captureDock').getBoundingClientRect().toJSON(),overflow:document.documentElement.scrollWidth>innerWidth,body:document.body.getBoundingClientRect().toJSON()}));assert.ok(Math.abs(d.nav.bottom-d.vh)<1,target+' bottom gap '+JSON.stringify(d));assert.equal(d.nav.width,width);assert.equal(d.overflow,false);if(target==='shot'){assert.ok(Math.abs(d.dock.bottom-d.nav.top)<1);assert.ok(d.main.height>0)}}}
await page.setViewportSize({width:393,height:852});await page.evaluate(()=>{go('shoot');document.getElementById('toast').classList.remove('show')});await page.screenshot({path:'test-output/footer-025-'+(engine===webkit?'webkit':'chromium')+'.png'});await page.evaluate(()=>go('shot'));await click('Borrar shot');await click('Cancelar');assert.equal(await page.evaluate(()=>shots().length),2);await click('Borrar shot');await page.locator('#deleteShotBtn').click();await page.getByRole('heading',{name:'IPSY Día 1',exact:true}).waitFor();assert.equal(await page.evaluate(()=>shots().length),1);assert.equal(await page.evaluate(()=>shots()[0].id),first);await page.evaluate(id=>selectShot(id),first);await page.waitForSelector('#sh');const mediaId=await page.evaluate(()=>raw().media[0].mediaId);await click('Borrar shot');await page.locator('#deleteShotBtn').click();await page.getByRole('heading',{name:'IPSY Día 1',exact:true}).waitFor();assert.equal(await page.evaluate(()=>shots().length),0);assert.equal(await page.evaluate(()=>p().days.length),0);assert.equal(await page.evaluate(id=>get('media',id),mediaId),undefined);assert.equal(await page.evaluate(()=>p().cameras.length),1);await page.reload();await page.getByRole('heading',{name:'IPSY Día 1',exact:true}).waitFor();assert.equal(await page.evaluate(()=>shots().length),0);
// Several registered cameras without an inherited selection require an explicit choice.
await page.evaluate(async()=>{p().cameras.push({...p().cameras[0],id:uid(),code:'CAM B'});await save();await createShot()});await page.getByRole('heading',{name:'Seleccionar equipo del shot',exact:true}).waitFor();assert.equal(await page.evaluate(()=>shots().length),0);await page.locator('#requiredCamera').selectOption({index:2});await click('Abrir shot');await page.waitForSelector('#sh');assert.equal(await page.evaluate(()=>raw().camera.cameraId),await page.evaluate(()=>p().cameras[1].id));
// Aborted deletion leaves both the shot and media intact.
await click('Borrar shot');await page.evaluate(()=>{window.originalTx=db.transaction.bind(db);db.transaction=(names,mode)=>{const tx=originalTx(names,mode);if(Array.isArray(names)&&names.includes('media'))queueMicrotask(()=>tx.abort());return tx}});await page.locator('#deleteShotBtn').click();await page.waitForFunction(()=>!shotDeleting);assert.equal(await page.evaluate(()=>shots().length),1);await page.evaluate(()=>{db.transaction=originalTx});await click('Cancelar');
// The generated file and its library remain available without a network.
if(engine===chromium){await page.evaluate(()=>navigator.serviceWorker.ready);await context.setOffline(true);await page.reload();await page.waitForSelector('#sh');await page.evaluate(()=>report());await page.waitForSelector('#savePDF');assert.ok(await page.evaluate(()=>preparedPDF.file.size>1000));await context.setOffline(false)}
assert.deepEqual(errors,[]);console.log('PASS '+(engine===webkit?'WebKit':'Chromium')+': equipment gates/assignment, actual named PDF download/share/offline, 30 footer layouts, shot deletion/cancel/rollback/media cleanup');await b.close()})().catch(e=>{console.error(e);process.exit(1)});


